In [1248]:
import pandas as pd
import json

In [1249]:
with open('../election-stations-2569.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# หาหน่วยเลือกตั้งของจังหวัด
rayong = next((p for p in data['provinces'] if p['name'] == 'ระยอง'), None)
# print(f"ระยอง {rayong['total_stations']} หน่วยเลือกตั้ง")
d = dict()
sd2d = dict()
t = 0
# หาหน่วยเลือกตั้งจากรหัส
def find_total_station(area,province):
    for p in data['provinces']:
        if p['name'] == province:
            for a in p['areas']:
                if a['area'] == area:
                    for unit in a['stations']:
                        if unit['district'] not in d:
                            d[unit['district']] = dict()
                        if unit['subdistrict'] not in  d[unit['district']]:
                            d[unit['district']][unit['subdistrict']] = 1
                            sd2d[unit['subdistrict']] = unit['district']
                        else:
                            d[unit['district']][unit['subdistrict']] += 1
    return None

find_total_station(2, 'ลำปาง')
print(d)
print(sd2d)
for k, v in d.items():
    for e, g in v.items():
        t+=g
print(t)

{'เมืองลำปาง': {'บ้านแลง': 12, 'บ้านเสด็จ': 19}, 'งาว': {'หลวงเหนือ': 7, 'หลวงใต้': 8, 'บ้านโป่ง': 12, 'บ้านร้อง': 13, 'ปงเตา': 13, 'นาแก': 6, 'บ้านอ้อน': 8, 'บ้านแหง': 9, 'บ้านหวด': 7, 'แม่ตีบ': 7}, 'แจ้ห่ม': {'แจ้ห่ม': 14, 'บ้านสา': 10, 'ปงดอน': 9, 'แม่สุก': 12, 'เมืองมาย': 7, 'ทุ่งผึ้ง': 8, 'วิเชตนคร': 12}, 'วังเหนือ': {'ทุ่งฮั้ว': 12, 'วังเหนือ': 12, 'วังใต้': 7, 'ร่องเคาะ': 18, 'วังทอง': 9, 'วังซ้าย': 10, 'วังแก้ว': 7, 'วังทรายคำ': 9}, 'เมืองปาน': {'เมืองปาน': 11, 'บ้านขอ': 14, 'ทุ่งกว๋าว': 16, 'แจ้ซ้อน': 15, 'หัวเมือง': 9}}
{'บ้านแลง': 'เมืองลำปาง', 'บ้านเสด็จ': 'เมืองลำปาง', 'หลวงเหนือ': 'งาว', 'หลวงใต้': 'งาว', 'บ้านโป่ง': 'งาว', 'บ้านร้อง': 'งาว', 'ปงเตา': 'งาว', 'นาแก': 'งาว', 'บ้านอ้อน': 'งาว', 'บ้านแหง': 'งาว', 'บ้านหวด': 'งาว', 'แม่ตีบ': 'งาว', 'แจ้ห่ม': 'แจ้ห่ม', 'บ้านสา': 'แจ้ห่ม', 'ปงดอน': 'แจ้ห่ม', 'แม่สุก': 'แจ้ห่ม', 'เมืองมาย': 'แจ้ห่ม', 'ทุ่งผึ้ง': 'แจ้ห่ม', 'วิเชตนคร': 'แจ้ห่ม', 'ทุ่งฮั้ว': 'วังเหนือ', 'วังเหนือ': 'วังเหนือ', 'วังใต้': 'วังเหนือ', 'ร่องเคาะ': 'วังเหนือ', 'วังทอง': 'วังเหนือ', 'วังซ้าย': 'วังเหนือ', 'วังแก้ว': 'วังเหนือ', 'วังทรายคำ': 'วังเหนือ', 'เมืองปาน': 'เมืองปาน', 'บ้านขอ': 'เมืองปาน', 'ทุ่งกว๋าว': 'เมืองปาน', 'แจ้ซ้อน': 'เมืองปาน', 'หัวเมือง': 'เมืองปาน'}
342

In [1250]:
d['นอกเขต'] = dict()
for i in range(1,14):
    sub_dist = f"ชุดที่ {i}"
    sd2d[sub_dist] = 'นอกเขต'
    d['นอกเขต'][sub_dist] = 1
    # all_subdistrict.append(sub_dist)

In [1251]:
d['วังเหนือ']['บ้านใหม่'] = 4
d['วังเหนือ']['วังเหนือ'] = 8
d['แจ้ห่ม']['แจ้ห่ม(ในเขต)'] = 6
d['แจ้ห่ม']['แจ้ห่ม(นอกเขต)'] = 8
d['แจ้ห่ม'].pop('แจ้ห่ม', None)
sd2d['บ้านใหม่'] = 'วังเหนือ'
sd2d['แจ้ห่ม(ในเขต)'] = "แจ้ห่ม"
sd2d['แจ้ห่ม(นอกเขต)'] = "แจ้ห่ม"

In [1252]:
all_distrcit = []
all_subdistrict = []
district_count = {}
for k,v in d.items():
    all_distrcit.append(k)
    all_subdistrict += v.keys()
    for key in v.keys():
        if k not in district_count:
            district_count[k] = v[key]
        else: district_count[k]+= v[key]

In [1253]:
for i in range(1,14):
    sub_dist = f"ชุดที่ {i}"
    all_subdistrict.append(sub_dist)

In [1254]:
df = pd.read_csv("../ocr-result1/master_results.csv")

In [1255]:
wrong_districts = []
for wrong_district in df['district'].unique().tolist():
    if wrong_district not in all_distrcit and wrong_district != 'นอกเขต':
        wrong_districts.append(wrong_district)

wrong_districts

[]

In [1256]:
from rapidfuzz import process
def automate_edit(feature, check, wrongs, df):
    wrong2correct = dict()
    scores = dict()
    lis = []
    for text in wrongs:
        match = process.extractOne(text, check, score_cutoff=50)

        if match:
            result, score, index = match
            wrong2correct[text] = result
            scores[text] = round(score,2)
            if scores[text] >= 70:
                df.loc[df[feature] == text, feature] = result
            else:
                lis.append(text)
            print(f"OCR: '{text}' -> Corrected: '{result}' (Confidence: {score:.2f}%)")
        else:
            wrong2correct[text] = "can't find"
            scores[text] = 0
            lis.append(text)
            print(f"OCR: '{text}' -> [Manual Review Needed]")
    return wrong2correct, scores, lis

In [1257]:
df_test = df.copy()
wrong2correct, scores, list_wrongs = automate_edit('district', all_distrcit, wrong_districts, df_test)

In [1258]:
wrong_sds = []
for wrong_sd in df_test['sub-district'].unique().tolist():
    if wrong_sd not in all_subdistrict:
        wrong_sds.append(wrong_sd)

wrong_sds

[]

In [1259]:
df_test.loc[df_test['sub-district'] == 'เเจ้ซ้อน', 'sub-district'] = 'แจ้ซ้อน'

In [1260]:
l = df_test['sub-district'].unique().tolist()
for sd in all_subdistrict:
    if sd not in l:
        print(f"เขต {sd} หายไปทั้ง บช และ เขต")

In [1261]:
df = df_test.copy()

In [1262]:
df['district'].unique().tolist()

['นอกเขต', 'งาว', 'วังเหนือ', 'เมืองปาน', 'เมืองลำปาง', 'แจ้ห่ม']

In [1263]:
correct_names = [
    "นางสาววิชุดา ว่องวัฒนวิโรจน์",
    "นางสาวสุวิภา กุศลจูง",
    "นายศรีพรหม หอมยก",
    "นายสมบูรณ์ รูปสะอาด",
    "นายดาชัย เอกปฐพี",
    "นายธนาธร โล่ห์สุนทร",
    "พันเอกสันทัด ภัทรกิตตินนท์",
]

In [1264]:
party2number = dict()
with open("../partys_lists_number.txt", 'r', encoding="utf-8") as f:
    lines = []
    for line in f:
        if line.strip() == "":continue
        num, party = line.strip().split(":")
        num = int(num.strip().split()[1])
        party = party.strip().removeprefix("พรรค")
        lines.append(party)
        party2number[party] = num
for i in range(1,8):
    party2number[correct_names[i-1]] = i
correct_names += lines

In [1265]:
correct_names

['นางสาววิชุดา ว่องวัฒนวิโรจน์',
 'นางสาวสุวิภา กุศลจูง',
 'นายศรีพรหม หอมยก',
 'นายสมบูรณ์ รูปสะอาด',
 'นายดาชัย เอกปฐพี',
 'นายธนาธร โล่ห์สุนทร',
 'พันเอกสันทัด ภัทรกิตตินนท์',
 'ไทยทรัพย์ทวี',
 'เพื่อชาติไทย',
 'ใหม่',
 'มิติใหม่',
 'รวมใจไทย',
 'รวมไทยสร้างชาติ',
 'พลวัต',
 'ประชาธิปไตยใหม่',
 'เพื่อไทย',
 'ทางเลือกใหม่',
 'เศรษฐกิจ',
 'เสรีรวมไทย',
 'รวมพลังประชาชน',
 'ท้องที่ไทย',
 'อนาคตไทย',
 'พลังเพื่อไทย',
 'ไทยชนะ',
 'พลังสังคมใหม่',
 'สังคมประชาธิปไตย',
 'ฟิวชัน',
 'ไทรวมพลัง',
 'ก้าวอิสระ',
 'ปวงชนไทย',
 'วิชชั่นใหม่',
 'เพื่อชีวิตใหม่',
 'คลองไทย',
 'ประชาธิปัตย์',
 'ไทยก้าวหน้า',
 'ไทยภักดี',
 'แรงงานสร้างชาติ',
 'ประชากรไทย',
 'ครูไทยเพื่อประชาชน',
 'ประชาชาติ',
 'สร้างอนาคตไทย',
 'รักชาติ',
 'ไทยพร้อม',
 'ภูมิใจไทย',
 'พลังธรรมใหม่',
 'กรีน',
 'ไทยธรรม',
 'แผ่นดินธรรม',
 'กล้าธรรม',
 'พลังประชารัฐ',
 'โอกาสใหม่',
 'เป็นธรรม',
 'ประชาชน',
 'ประชาไทย',
 'ไทยสร้างไทย',
 'ไทยก้าวใหม่',
 'ประชาอาสาชาติ',
 'พร้อม',
 'เครือข่ายชาวนาแห่งประเทศไทย',
 'ไทยพิทักษ์ธรรม',
 'ความหวังใหม่',
 'ไทยรวมไทย',
 'เพื่อบ้านเมือง',
 'พลังไทยรักชาติ']

In [1266]:
df_test = df.copy()

In [1267]:
wrong_names = []
for wrong_name in df_test['name'].unique().tolist():
    if wrong_name not in all_subdistrict:
        wrong_names.append(wrong_name)

wrong_names

['ไทยทรัพย์ทวี',
 'เพื่อชาติไทย',
 'ใหม่',
 'มิติใหม่',
 'รวมใจไทย',
 'รวมไทยสร้างชาติ',
 'พลวัต',
 'ประชาธิปไตยใหม่',
 'เพื่อไทย',
 'ทางเลือกใหม่',
 'เศรษฐกิจ',
 'เสรีรวมไทย',
 'รวมพลังประชาชน',
 'ท้องที่ไทย',
 'อนาคตไทย',
 'พลังเพื่อไทย',
 'ไทยชนะ',
 'พลังสังคมใหม่',
 'สังคมประชาธิปไตย',
 'ฟิวชัน',
 'ไทรวมพลัง',
 'ก้าวอิสระ',
 'ปวงชนไทย',
 'วิชชั่นใหม่',
 'เพื่อชีวิตใหม่',
 'คลองไทย',
 'ประชาธิปัตย์',
 'ไทยก้าวหน้า',
 'ไทยภักดี',
 'แรงงานสร้างชาติ',
 'ประชากรไทย',
 'ครูไทยเพื่อประชาชน',
 'ประชาชาติ',
 'สร้างอนาคตไทย',
 'รักชาติ',
 'ไทยพร้อม',
 'ภูมิใจไทย',
 'พลังธรรมใหม่',
 'กรีน',
 'ไทยธรรม',
 'แผ่นดินธรรม',
 'กล้าธรรม',
 'พลังประชารัฐ',
 'โอกาสใหม่',
 'เป็นธรรม',
 'ประชาชน',
 'ประชาไทย',
 'ไทยสร้างไทย',
 'ไทยก้าวใหม่',
 'ประชาอาสาชาติ',
 'พร้อม',
 'เครือข่ายชาวนาแห่งประเทศไทย',
 'ไทยพิทักษ์ธรรม',
 'ความหวังใหม่',
 'ไทยรวมไทย',
 'เพื่อบ้านเมือง',
 'พลังไทยรักชาติ',
 'นางสาววิชุดา ว่องวัฒนวิโรจน์',
 'นางสาวสุวิภา กุศลจูง',
 'นายศรีพรหม หอมยก',
 'นายสมบูรณ์ รูปสะอาด',
 'นายดาชัย เอกปฐพี',
 'นายธนาธร โล่ห์สุนทร',
 'พันเอกสันทัด ภัทรกิตตินนท์']

In [1268]:
wrong2correct, scores, list_wrongs = automate_edit('name', correct_names, wrong_names, df_test)

OCR: 'ไทยทรัพย์ทวี' -> Corrected: 'ไทยทรัพย์ทวี' (Confidence: 100.00%)
OCR: 'เพื่อชาติไทย' -> Corrected: 'เพื่อชาติไทย' (Confidence: 100.00%)
OCR: 'ใหม่' -> Corrected: 'ใหม่' (Confidence: 100.00%)
OCR: 'มิติใหม่' -> Corrected: 'มิติใหม่' (Confidence: 100.00%)
OCR: 'รวมใจไทย' -> Corrected: 'รวมใจไทย' (Confidence: 100.00%)
OCR: 'รวมไทยสร้างชาติ' -> Corrected: 'รวมไทยสร้างชาติ' (Confidence: 100.00%)
OCR: 'พลวัต' -> Corrected: 'พลวัต' (Confidence: 100.00%)
OCR: 'ประชาธิปไตยใหม่' -> Corrected: 'ประชาธิปไตยใหม่' (Confidence: 100.00%)
OCR: 'เพื่อไทย' -> Corrected: 'เพื่อไทย' (Confidence: 100.00%)
OCR: 'ทางเลือกใหม่' -> Corrected: 'ทางเลือกใหม่' (Confidence: 100.00%)
OCR: 'เศรษฐกิจ' -> Corrected: 'เศรษฐกิจ' (Confidence: 100.00%)
OCR: 'เสรีรวมไทย' -> Corrected: 'เสรีรวมไทย' (Confidence: 100.00%)
OCR: 'รวมพลังประชาชน' -> Corrected: 'รวมพลังประชาชน' (Confidence: 100.00%)
OCR: 'ท้องที่ไทย' -> Corrected: 'ท้องที่ไทย' (Confidence: 100.00%)
OCR: 'อนาคตไทย' -> Corrected: 'อนาคตไทย' (Confidence: 100.00%)
OCR: 'พลังเพื่อไทย' -> Corrected: 'พลังเพื่อไทย' (Confidence: 100.00%)
OCR: 'ไทยชนะ' -> Corrected: 'ไทยชนะ' (Confidence: 100.00%)
OCR: 'พลังสังคมใหม่' -> Corrected: 'พลังสังคมใหม่' (Confidence: 100.00%)
OCR: 'สังคมประชาธิปไตย' -> Corrected: 'สังคมประชาธิปไตย' (Confidence: 100.00%)
OCR: 'ฟิวชัน' -> Corrected: 'ฟิวชัน' (Confidence: 100.00%)
OCR: 'ไทรวมพลัง' -> Corrected: 'ไทรวมพลัง' (Confidence: 100.00%)
OCR: 'ก้าวอิสระ' -> Corrected: 'ก้าวอิสระ' (Confidence: 100.00%)
OCR: 'ปวงชนไทย' -> Corrected: 'ปวงชนไทย' (Confidence: 100.00%)
OCR: 'วิชชั่นใหม่' -> Corrected: 'วิชชั่นใหม่' (Confidence: 100.00%)
OCR: 'เพื่อชีวิตใหม่' -> Corrected: 'เพื่อชีวิตใหม่' (Confidence: 100.00%)
OCR: 'คลองไทย' -> Corrected: 'คลองไทย' (Confidence: 100.00%)
OCR: 'ประชาธิปัตย์' -> Corrected: 'ประชาธิปัตย์' (Confidence: 100.00%)
OCR: 'ไทยก้าวหน้า' -> Corrected: 'ไทยก้าวหน้า' (Confidence: 100.00%)
OCR: 'ไทยภักดี' -> Corrected: 'ไทยภักดี' (Confidence: 100.00%)
OCR: 'แรงงานสร้างชาติ' -> Corrected: 'แรงงานสร้างชาติ' (Confidence: 100.00%)
OCR: 'ประชากรไทย' -> Corrected: 'ประชากรไทย' (Confidence: 100.00%)
OCR: 'ครูไทยเพื่อประชาชน' -> Corrected: 'ครูไทยเพื่อประชาชน' (Confidence: 100.00%)
OCR: 'ประชาชาติ' -> Corrected: 'ประชาชาติ' (Confidence: 100.00%)
OCR: 'สร้างอนาคตไทย' -> Corrected: 'สร้างอนาคตไทย' (Confidence: 100.00%)
OCR: 'รักชาติ' -> Corrected: 'รักชาติ' (Confidence: 100.00%)
OCR: 'ไทยพร้อม' -> Corrected: 'ไทยพร้อม' (Confidence: 100.00%)
OCR: 'ภูมิใจไทย' -> Corrected: 'ภูมิใจไทย' (Confidence: 100.00%)
OCR: 'พลังธรรมใหม่' -> Corrected: 'พลังธรรมใหม่' (Confidence: 100.00%)
OCR: 'กรีน' -> Corrected: 'กรีน' (Confidence: 100.00%)
OCR: 'ไทยธรรม' -> Corrected: 'ไทยธรรม' (Confidence: 100.00%)
OCR: 'แผ่นดินธรรม' -> Corrected: 'แผ่นดินธรรม' (Confidence: 100.00%)
OCR: 'กล้าธรรม' -> Corrected: 'กล้าธรรม' (Confidence: 100.00%)
OCR: 'พลังประชารัฐ' -> Corrected: 'พลังประชารัฐ' (Confidence: 100.00%)
OCR: 'โอกาสใหม่' -> Corrected: 'โอกาสใหม่' (Confidence: 100.00%)
OCR: 'เป็นธรรม' -> Corrected: 'เป็นธรรม' (Confidence: 100.00%)
OCR: 'ประชาชน' -> Corrected: 'ประชาชน' (Confidence: 100.00%)
OCR: 'ประชาไทย' -> Corrected: 'ประชาไทย' (Confidence: 100.00%)
OCR: 'ไทยสร้างไทย' -> Corrected: 'ไทยสร้างไทย' (Confidence: 100.00%)
OCR: 'ไทยก้าวใหม่' -> Corrected: 'ไทยก้าวใหม่' (Confidence: 100.00%)
OCR: 'ประชาอาสาชาติ' -> Corrected: 'ประชาอาสาชาติ' (Confidence: 100.00%)
OCR: 'พร้อม' -> Corrected: 'พร้อม' (Confidence: 100.00%)
OCR: 'เครือข่ายชาวนาแห่งประเทศไทย' -> Corrected: 'เครือข่ายชาวนาแห่งประเทศไทย' (Confidence: 100.00%)
OCR: 'ไทยพิทักษ์ธรรม' -> Corrected: 'ไทยพิทักษ์ธรรม' (Confidence: 100.00%)
OCR: 'ความหวังใหม่' -> Corrected: 'ความหวังใหม่' (Confidence: 100.00%)
OCR: 'ไทยรวมไทย' -> Corrected: 'ไทยรวมไทย' (Confidence: 100.00%)
OCR: 'เพื่อบ้านเมือง' -> Corrected: 'เพื่อบ้านเมือง' (Confidence: 100.00%)
OCR: 'พลังไทยรักชาติ' -> Corrected: 'พลังไทยรักชาติ' (Confidence: 100.00%)
OCR: 'นางสาววิชุดา ว่องวัฒนวิโรจน์' -> Corrected: 'นางสาววิชุดา ว่องวัฒนวิโรจน์' (Confidence: 100.00%)
OCR: 'นางสาวสุวิภา กุศลจูง' -> Corrected: 'นางสาวสุวิภา กุศลจูง' (Confidence: 100.00%)
OCR: 'นายศรีพรหม หอมยก' -> Corrected: 'นายศรีพรหม หอมยก' (Confidence: 100.00%)
OCR: 'นายสมบูรณ์ รูปสะอาด' -> Corrected: 'นายสมบูรณ์ รูปสะอาด' (Confidence: 100.00%)
OCR: 'นายดาชัย เอกปฐพี' -> Corrected: 'นายดาชัย เอกปฐพี' (Confidence: 100.00%)
OCR: 'นายธนาธร โล่ห์สุนทร' -> Corrected: 'นายธนาธร โล่ห์สุนทร' (Confidence: 100.00%)
OCR: 'พันเอกสันทัด ภัทรกิตตินนท์' -> Corrected: 'พันเอกสันทัด ภัทรกิตตินนท์' (Confidence: 100.00%)

In [1269]:
list_wrongs

[]

In [1270]:
wrong2correct = {
    "พิวซัน": 'ฟิวชัน',
    "ก้าวล่วง": 'ก้าวอิสระ',
    "พิวจัน":"ฟิวชัน",
    "พิกุลัน":"ฟิวชัน",
    "พิวจันทร์":"ฟิวชัน",
    "พิวซิน":"ฟิวชัน",
    "พิวขัน":"ฟิวชัน",
    "กษิน":"กรีน",
    "วิชัยขับใหญ่":"วิชชั่นใหม่",
    "พิชัย":"ฟิวชัน",
    "ทรอม":"พร้อม",
    "พืชขัน":"ฟิวชัน",
    "พืชชัน":"ฟิวชัน",
    "วิภาวดี":"รักชาติ",
    "กรุงเทพมหานคร":"กรีน",
    "ไทยทรัพยากร":"ไทยทรัพย์ทวี",
    "พลังประจวบ":"พลังประชารัฐ",
    "พิวัฒน์":"ฟิวชัน",
    "กวิน":"กรีน",
    "ดร.ณฐภัทร":"เศรษฐกิจ",
    "ศรีราชาไทย":"เสรีรวมไทย",
    "พิมพ์ขึ้น":"ฟิวชัน", 
    "โทรสารเคล็ง":"ไทรวมพลัง",
    "กำกวติสร":"ก้าวอิสระ",
    "พิกุลชน":"ฟิวชัน",
    "นางสาววิฤดา วงศ์พรมไพรณ์":correct_names[0],
    "พิกวัน":"ฟิวชัน",
    "พืชซัน":"ฟิวชัน",
    "พืชชน":"ฟิวชัน",
    "ฟิลิปปิน":"ฟิวชัน",
    "ไทกรุงเทพฯ":"ไทรวมพลัง",
    "ก้าวก้มลง":"ก้าวอิสระ",
    "พิกขัน":"ฟิวชัน",
    "พิกุล":"ฟิวชัน",
    "กำกวติสระ":"ก้าวอิสระ"
}

In [1271]:
for wrong in list_wrongs:
    print(df_test[df_test['name'] == wrong])

In [1272]:
for wrong, correct in wrong2correct.items():
    df_test.loc[df_test['name'] == wrong, 'name'] = correct

In [1273]:
for wrong in list_wrongs:
    print(df_test[df_test['name'] == wrong])

In [1274]:
for i in df_test['name'].unique().tolist():
    if i not in correct_names:
        print(i)

In [1275]:
df_test.shape

(21496, 7)

In [1276]:
df = df_test.copy()

In [1277]:
def check_from_df(df):
    expected_khet = set(correct_names[:7])
    expected_bch = set(correct_names[7:])
    
    df['name'] = df['name'].astype(str).str.strip()
    
    print("🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...\n")
    has_error = False
    
    # 3. จัดกลุ่มตรวจสอบ (เพิ่ม 'district' เข้าไปในวงเล็บ)
    grouped = df.groupby(['district', 'sub-district', 'unit_number', 'type'])
    total = 0
    
    # เพิ่ม district มารับค่าในลูปด้วย
    for (district, sub_district, unit_number, type_val), group_data in grouped:
        # ดึงชื่อออกมาเป็น List (เพื่อนับซ้ำ) และ Set (เพื่อหาตัวที่ขาด/เกิน)
        actual_names_list = group_data['name'].tolist()
        actual_names_set = set(actual_names_list)
        
        if type_val == 'เขต':
            expected_names = expected_khet
        elif type_val == 'บช':
            expected_names = expected_bch
        else:
            continue 
        
        expected_total = len(expected_names)
    
        # --- เริ่มกระบวนการตรวจสอบ 3 ชั้น ---
        
        # 1. เช็คขาด (Missing)
        missing = expected_names - actual_names_set
        
        # 2. เช็คแปลกปลอม (Extra/Unrecognized)
        extra = actual_names_set - expected_names
        
        # 3. เช็คซ้ำซ้อน (Duplicates)
        name_counts = group_data['name'].value_counts()
        duplicates = name_counts[name_counts > 1].index.tolist()
    
        # ถ้าเจอความผิดปกติอย่างใดอย่างหนึ่ง ให้ปริ้นท์แจ้งเตือน
        if missing or extra or duplicates:
            has_error = True
            
            # 📌 แก้ไขบรรทัด Print ให้แสดง "อำเภอ" ด้วย
            print(f"📌 [{type_val}] อำเภอ: {district} | ตำบล: {sub_district} | หน่วยที่: {unit_number}")
            print(f"   📊 มีข้อมูลทั้งหมด {len(actual_names_list)} บรรทัด (จากที่ควรมี {expected_total} บรรทัด)")
            
            if missing:
                print(f"   ❌ ขาดหายไป {len(missing)} รายชื่อ: {', '.join(sorted(missing))}")
                total += len(missing)
            if extra:
                print(f"   🚨 แปลกปลอม/ผิดสเปก {len(extra)} รายชื่อ: {', '.join(sorted(extra))}")
                
            if duplicates:
                print(f"   🔄 รายชื่อซ้ำซ้อน {len(duplicates)} รายการ:")
                for dup in duplicates:
                    print(f"      - '{dup}' โผล่มา {name_counts[dup]} บรรทัด")
                    
            print("-" * 60)
            
    print(f"จำนวนที่ขาดรวมคิดเป็น: {total}")
    if not has_error:
        print("✅ ข้อมูลสมบูรณ์แบบ! ทุกหน่วยมีรายชื่อครบถ้วน ไม่มีขาด ไม่มีเกิน ไม่มีซ้ำครับ")

In [1278]:
def edit_df(previous_val, old_val, new_val, df):

    previous_name = df.groupby(['district', 'sub-district', 'unit_number', 'type'])['name'].shift(1)

    condition_fix = (df['name'] == old_val) & (previous_name == previous_val)

    rows_to_fix = condition_fix.sum()

    if rows_to_fix > 0:
        df.loc[condition_fix, 'name'] = new_val
        print(f"✅ แก้ไขพรรค {old_val} เป็น {new_val} (ที่อยู่ต่อจาก {previous_val}) สำเร็จจำนวน {rows_to_fix} แถว")
    else:
        print(f"✅ ไม่พบเคสที่พรรค {old_val} อยู่ต่อจาก {previous_val}")

In [1279]:
check_from_df(df)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

📌 [บช] อำเภอ: งาว | ตำบล: นาแก | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 55 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 2 รายชื่อ: เพื่อชาติไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านแหง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 10 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 47 รายชื่อ: กรีน, กล้าธรรม, ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ความหวังใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชน, ประชาชาติ, ประชาธิปัตย์, ประชาอาสาชาติ, ประชาไทย, ปวงชนไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังสังคมใหม่, พลังเพื่อไทย, พลังไทยรักชาติ, ฟิวชัน, ภูมิใจไทย, รวมพลังประชาชน, รักชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อชีวิตใหม่, เพื่อบ้านเมือง, เศรษฐกิจ, เสรีรวมไทย, แผ่นดินธรรม, แรงงานสร้างชาติ, โอกาสใหม่, ไทยก้าวหน้า, ไทยก้าวใหม่, ไทยชนะ, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยภักดี, ไทยรวมไทย, ไทยสร้างไทย, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 12
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: หลวงใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: แม่ตีบ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ท้องที่ไทย, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังซ้าย | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทอง | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 15
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 31 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 26 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 8
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 13
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 56 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 1 รายชื่อ: ท้องที่ไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)

In [1280]:
edit_df("ปวงชนไทย","ใหม่", "วิชชั่นใหม่", df)

✅ ไม่พบเคสที่พรรค ใหม่ อยู่ต่อจาก ปวงชนไทย

In [1281]:
check_from_df(df)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

📌 [บช] อำเภอ: งาว | ตำบล: นาแก | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 55 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 2 รายชื่อ: เพื่อชาติไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านแหง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 10 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 47 รายชื่อ: กรีน, กล้าธรรม, ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ความหวังใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชน, ประชาชาติ, ประชาธิปัตย์, ประชาอาสาชาติ, ประชาไทย, ปวงชนไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังสังคมใหม่, พลังเพื่อไทย, พลังไทยรักชาติ, ฟิวชัน, ภูมิใจไทย, รวมพลังประชาชน, รักชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อชีวิตใหม่, เพื่อบ้านเมือง, เศรษฐกิจ, เสรีรวมไทย, แผ่นดินธรรม, แรงงานสร้างชาติ, โอกาสใหม่, ไทยก้าวหน้า, ไทยก้าวใหม่, ไทยชนะ, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยภักดี, ไทยรวมไทย, ไทยสร้างไทย, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 12
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: หลวงใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: แม่ตีบ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ท้องที่ไทย, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังซ้าย | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทอง | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 15
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 31 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 26 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 8
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 13
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 56 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 1 รายชื่อ: ท้องที่ไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)

In [1282]:
edit_df("ไทยสร้างไทย", 'ใหม่', "ไทยก้าวใหม่", df)

✅ ไม่พบเคสที่พรรค ใหม่ อยู่ต่อจาก ไทยสร้างไทย

In [1283]:
check_from_df(df)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

📌 [บช] อำเภอ: งาว | ตำบล: นาแก | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 55 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 2 รายชื่อ: เพื่อชาติไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านแหง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 10 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 47 รายชื่อ: กรีน, กล้าธรรม, ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ความหวังใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชน, ประชาชาติ, ประชาธิปัตย์, ประชาอาสาชาติ, ประชาไทย, ปวงชนไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังสังคมใหม่, พลังเพื่อไทย, พลังไทยรักชาติ, ฟิวชัน, ภูมิใจไทย, รวมพลังประชาชน, รักชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อชีวิตใหม่, เพื่อบ้านเมือง, เศรษฐกิจ, เสรีรวมไทย, แผ่นดินธรรม, แรงงานสร้างชาติ, โอกาสใหม่, ไทยก้าวหน้า, ไทยก้าวใหม่, ไทยชนะ, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยภักดี, ไทยรวมไทย, ไทยสร้างไทย, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 12
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: หลวงใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: แม่ตีบ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ท้องที่ไทย, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังซ้าย | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทอง | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 15
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 31 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 26 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 8
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 13
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 56 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 1 รายชื่อ: ท้องที่ไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)

In [1284]:
edit_df("พลวัต", "ใหม่", "ประชาธิปไตยใหม่", df)

✅ ไม่พบเคสที่พรรค ใหม่ อยู่ต่อจาก พลวัต

In [1285]:
check_from_df(df)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

📌 [บช] อำเภอ: งาว | ตำบล: นาแก | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 55 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 2 รายชื่อ: เพื่อชาติไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านแหง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 10 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 47 รายชื่อ: กรีน, กล้าธรรม, ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ความหวังใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชน, ประชาชาติ, ประชาธิปัตย์, ประชาอาสาชาติ, ประชาไทย, ปวงชนไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังสังคมใหม่, พลังเพื่อไทย, พลังไทยรักชาติ, ฟิวชัน, ภูมิใจไทย, รวมพลังประชาชน, รักชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อชีวิตใหม่, เพื่อบ้านเมือง, เศรษฐกิจ, เสรีรวมไทย, แผ่นดินธรรม, แรงงานสร้างชาติ, โอกาสใหม่, ไทยก้าวหน้า, ไทยก้าวใหม่, ไทยชนะ, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยภักดี, ไทยรวมไทย, ไทยสร้างไทย, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 12
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: หลวงใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: แม่ตีบ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ท้องที่ไทย, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังซ้าย | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทอง | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 15
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 31 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 26 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 8
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 13
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 56 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 1 รายชื่อ: ท้องที่ไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)

In [1286]:
df.shape

(21496, 7)

In [1287]:
print(df[(df['sub-district'] == 'ทุ่งฮั้ว') & (df['unit_number'] == 7)].to_string())

     type province  district sub-district  unit_number                          name score
6366  เขต    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7  นางสาววิชุดา ว่องวัฒนวิโรจน์    21
6367  เขต    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7          นางสาวสุวิภา กุศลจูง    57
6368  เขต    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7              นายศรีพรหม หอมยก     3
6369  เขต    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7           นายสมบูรณ์ รูปสะอาด     3
6370  เขต    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7              นายดาชัย เอกปฐพี    12
6371  เขต    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7           นายธนาธร โล่ห์สุนทร    45
6372  เขต    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7    พันเอกสันทัด ภัทรกิตตินนท์     2
7321   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                  ไทยทรัพย์ทวี     3
7322   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                  เพื่อชาติไทย     8
7323   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                          ใหม่     0
7324   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      มิติใหม่     1
7325   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      รวมใจไทย     7
7326   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7               รวมไทยสร้างชาติ     7
7327   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                         พลวัต     2
7328   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7               ประชาธิปไตยใหม่     0
7329   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      เพื่อไทย    16
7330   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                  ทางเลือกใหม่     1
7331   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      เศรษฐกิจ     3
7332   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                    เสรีรวมไทย     0
7333   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                รวมพลังประชาชน     0
7334   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                    ท้องที่ไทย     0
7335   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      อนาคตไทย     0
7336   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                  พลังเพื่อไทย     0
7337   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                        ไทยชนะ     0
7338   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                 พลังสังคมใหม่     1
7339   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7              สังคมประชาธิปไตย     0
7340   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                        ฟิวชัน     0
7341   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                     ไทรวมพลัง     0
7342   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                     ก้าวอิสระ     0
7343   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      ปวงชนไทย     0
7344   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                   วิชชั่นใหม่     1
7345   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                เพื่อชีวิตใหม่     0
7346   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                       คลองไทย     0
7347   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                  ประชาธิปัตย์    43
7348   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                   ไทยก้าวหน้า     0
7349   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      ไทยภักดี     0
7350   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7               แรงงานสร้างชาติ     0
7351   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                    ประชากรไทย     1
7352   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7            ครูไทยเพื่อประชาชน     0
7353   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                     ประชาชาติ     0
7354   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                 สร้างอนาคตไทย     0
7355   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                       รักชาติ     1
7356   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      ไทยพร้อม     2
7357   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                     ภูมิใจไทย     3
7358   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                  พลังธรรมใหม่     1
7359   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                          กรีน     0
7360   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                       ไทยธรรม     0
7361   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                   แผ่นดินธรรม     0
7362   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      กล้าธรรม     0
7363   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                  พลังประชารัฐ     1
7364   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                     โอกาสใหม่     0
7365   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      เป็นธรรม     1
7366   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                       ประชาชน     4
7367   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                      ประชาไทย     2
7368   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                   ไทยสร้างไทย     0
7369   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                   ไทยก้าวใหม่     0
7370   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                 ประชาอาสาชาติ     0
7371   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                         พร้อม     0
7372   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7   เครือข่ายชาวนาแห่งประเทศไทย     0
7373   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                ไทยพิทักษ์ธรรม     0
7374   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                  ความหวังใหม่     0
7375   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                     ไทยรวมไทย     0
7376   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                เพื่อบ้านเมือง     0
7377   บช    ลำปาง  วังเหนือ     ทุ่งฮั้ว            7                พลังไทยรักชาติ     0

In [1288]:
edit_df("ก้าวอิสระ", "ประชาไทย", "ปวงชนไทย", df)
edit_df("ปวงชนไทย", "ใหม่", "วิชชั่นใหม่", df)
check_from_df(df)

✅ ไม่พบเคสที่พรรค ประชาไทย อยู่ต่อจาก ก้าวอิสระ
✅ ไม่พบเคสที่พรรค ใหม่ อยู่ต่อจาก ปวงชนไทย
🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

📌 [บช] อำเภอ: งาว | ตำบล: นาแก | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 55 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 2 รายชื่อ: เพื่อชาติไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านแหง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 10 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 47 รายชื่อ: กรีน, กล้าธรรม, ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ความหวังใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชน, ประชาชาติ, ประชาธิปัตย์, ประชาอาสาชาติ, ประชาไทย, ปวงชนไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังสังคมใหม่, พลังเพื่อไทย, พลังไทยรักชาติ, ฟิวชัน, ภูมิใจไทย, รวมพลังประชาชน, รักชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อชีวิตใหม่, เพื่อบ้านเมือง, เศรษฐกิจ, เสรีรวมไทย, แผ่นดินธรรม, แรงงานสร้างชาติ, โอกาสใหม่, ไทยก้าวหน้า, ไทยก้าวใหม่, ไทยชนะ, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยภักดี, ไทยรวมไทย, ไทยสร้างไทย, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 12
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: หลวงใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: แม่ตีบ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ท้องที่ไทย, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังซ้าย | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทอง | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 15
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 31 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 26 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 8
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 13
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 56 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 1 รายชื่อ: ท้องที่ไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 5

In [1289]:
print(df[(df['sub-district'] == 'บ้านสา') & (df['unit_number'] == 1)].to_string())

      type province district sub-district  unit_number                          name score
17081  เขต    ลำปาง   แจ้ห่ม       บ้านสา            1  นางสาววิชุดา ว่องวัฒนวิโรจน์    13
17082  เขต    ลำปาง   แจ้ห่ม       บ้านสา            1          นางสาวสุวิภา กุศลจูง    99
17083  เขต    ลำปาง   แจ้ห่ม       บ้านสา            1              นายศรีพรหม หอมยก    11
17084  เขต    ลำปาง   แจ้ห่ม       บ้านสา            1           นายสมบูรณ์ รูปสะอาด     8
17085  เขต    ลำปาง   แจ้ห่ม       บ้านสา            1              นายดาชัย เอกปฐพี    10
17086  เขต    ลำปาง   แจ้ห่ม       บ้านสา            1           นายธนาธร โล่ห์สุนทร    54
17087  เขต    ลำปาง   แจ้ห่ม       บ้านสา            1    พันเอกสันทัด ภัทรกิตตินนท์    11
17529   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                  ไทยทรัพย์ทวี     0
17530   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                  เพื่อชาติไทย     9
17531   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                          ใหม่     1
17532   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      มิติใหม่     1
17533   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      รวมใจไทย     2
17534   บช    ลำปาง   แจ้ห่ม       บ้านสา            1               รวมไทยสร้างชาติ     9
17535   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                         พลวัต     0
17536   บช    ลำปาง   แจ้ห่ม       บ้านสา            1               ประชาธิปไตยใหม่     0
17537   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      เพื่อไทย    43
17538   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                  ทางเลือกใหม่     2
17539   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      เศรษฐกิจ     8
17540   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                    เสรีรวมไทย     0
17541   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                รวมพลังประชาชน     2
17542   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                    ท้องที่ไทย     0
17543   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      อนาคตไทย     0
17544   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                  พลังเพื่อไทย     2
17545   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                        ไทยชนะ     1
17546   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                 พลังสังคมใหม่     0
17547   บช    ลำปาง   แจ้ห่ม       บ้านสา            1              สังคมประชาธิปไตย     0
17548   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                        ฟิวชัน     0
17549   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                     ไทรวมพลัง     0
17550   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                     ก้าวอิสระ     1
17551   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      ปวงชนไทย     0
17552   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                   วิชชั่นใหม่     1
17553   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                เพื่อชีวิตใหม่     0
17554   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                       คลองไทย     1
17555   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                  ประชาธิปัตย์     1
17556   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                   ไทยก้าวหน้า     0
17557   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      ไทยภักดี     1
17558   บช    ลำปาง   แจ้ห่ม       บ้านสา            1               แรงงานสร้างชาติ     2
17559   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                    ประชากรไทย     1
17560   บช    ลำปาง   แจ้ห่ม       บ้านสา            1            ครูไทยเพื่อประชาชน     0
17561   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                     ประชาชาติ     1
17562   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                 สร้างอนาคตไทย     0
17563   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                       รักชาติ     0
17564   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      ไทยพร้อม     2
17565   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                     ภูมิใจไทย    23
17566   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                  พลังธรรมใหม่     0
17567   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                          กรีน     0
17568   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                       ไทยธรรม     1
17569   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                   แผ่นดินธรรม     0
17570   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      กล้าธรรม     3
17571   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                  พลังประชารัฐ     0
17572   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                     โอกาสใหม่     0
17573   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      เป็นธรรม     0
17574   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                       ประชาชน    50
17575   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                      ประชาไทย     0
17576   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                   ไทยสร้างไทย     1
17577   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                   ไทยก้าวใหม่     0
17578   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                 ประชาอาสาชาติ     0
17579   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                         พร้อม     0
17580   บช    ลำปาง   แจ้ห่ม       บ้านสา            1   เครือข่ายชาวนาแห่งประเทศไทย     0
17581   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                ไทยพิทักษ์ธรรม     0
17582   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                  ความหวังใหม่     0
17583   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                     ไทยรวมไทย     0
17584   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                เพื่อบ้านเมือง     0
17585   บช    ลำปาง   แจ้ห่ม       บ้านสา            1                พลังไทยรักชาติ     0

In [1290]:
edit_df("วิชชั่นใหม่", "เพื่อชาติไทย", "เพื่อชีวิตใหม่", df)

✅ ไม่พบเคสที่พรรค เพื่อชาติไทย อยู่ต่อจาก วิชชั่นใหม่

In [1291]:
print(df[(df['sub-district'] == 'วังทอง') & (df['unit_number'] == 9)].to_string())

      type province  district sub-district  unit_number                          name score
6730   เขต    ลำปาง  วังเหนือ       วังทอง            9  นางสาววิชุดา ว่องวัฒนวิโรจน์     7
6731   เขต    ลำปาง  วังเหนือ       วังทอง            9          นางสาวสุวิภา กุศลจูง    48
6732   เขต    ลำปาง  วังเหนือ       วังทอง            9              นายศรีพรหม หอมยก     3
6733   เขต    ลำปาง  วังเหนือ       วังทอง            9           นายสมบูรณ์ รูปสะอาด     0
6734   เขต    ลำปาง  วังเหนือ       วังทอง            9              นายดาชัย เอกปฐพี   142
6735   เขต    ลำปาง  วังเหนือ       วังทอง            9           นายธนาธร โล่ห์สุนทร    26
6736   เขต    ลำปาง  วังเหนือ       วังทอง            9    พันเอกสันทัด ภัทรกิตตินนท์     4
10172   บช    ลำปาง  วังเหนือ       วังทอง            9                  ไทยทรัพย์ทวี     ☑
10173   บช    ลำปาง  วังเหนือ       วังทอง            9                  เพื่อชาติไทย     ☐
10174   บช    ลำปาง  วังเหนือ       วังทอง            9                          ใหม่     ☐
10175   บช    ลำปาง  วังเหนือ       วังทอง            9                      มิติใหม่     ☐
10176   บช    ลำปาง  วังเหนือ       วังทอง            9                      รวมใจไทย     ☐
10177   บช    ลำปาง  วังเหนือ       วังทอง            9               รวมไทยสร้างชาติ     ☐
10178   บช    ลำปาง  วังเหนือ       วังทอง            9                         พลวัต     ☐
10179   บช    ลำปาง  วังเหนือ       วังทอง            9               ประชาธิปไตยใหม่     ☐
10180   บช    ลำปาง  วังเหนือ       วังทอง            9                      เพื่อไทย     ☐
10181   บช    ลำปาง  วังเหนือ       วังทอง            9                  ทางเลือกใหม่     ☐
10182   บช    ลำปาง  วังเหนือ       วังทอง            9                      เศรษฐกิจ     1
10183   บช    ลำปาง  วังเหนือ       วังทอง            9                    เสรีรวมไทย   ( )
10184   บช    ลำปาง  วังเหนือ       วังทอง            9                รวมพลังประชาชน     5
10185   บช    ลำปาง  วังเหนือ       วังทอง            9                    ท้องที่ไทย     1
10186   บช    ลำปาง  วังเหนือ       วังทอง            9                      อนาคตไทย   ( )
10187   บช    ลำปาง  วังเหนือ       วังทอง            9                  พลังเพื่อไทย     2
10188   บช    ลำปาง  วังเหนือ       วังทอง            9                        ไทยชนะ     4
10189   บช    ลำปาง  วังเหนือ       วังทอง            9                 พลังสังคมใหม่   ( )
10190   บช    ลำปาง  วังเหนือ       วังทอง            9              สังคมประชาธิปไตย   ( )
10191   บช    ลำปาง  วังเหนือ       วังทอง            9                        ฟิวชัน   ( )
10192   บช    ลำปาง  วังเหนือ       วังทอง            9                     ไทรวมพลัง     1
10193   บช    ลำปาง  วังเหนือ       วังทอง            9                     ก้าวอิสระ     1
10194   บช    ลำปาง  วังเหนือ       วังทอง            9                      ปวงชนไทย   ( )
10195   บช    ลำปาง  วังเหนือ       วังทอง            9                   วิชชั่นใหม่   ( )
10196   บช    ลำปาง  วังเหนือ       วังทอง            9                เพื่อชีวิตใหม่     1
10197   บช    ลำปาง  วังเหนือ       วังทอง            9                       คลองไทย   ( )
10198   บช    ลำปาง  วังเหนือ       วังทอง            9                  ประชาธิปัตย์    20
10199   บช    ลำปาง  วังเหนือ       วังทอง            9                   ไทยก้าวหน้า     2
10200   บช    ลำปาง  วังเหนือ       วังทอง            9                      ไทยภักดี     1
10201   บช    ลำปาง  วังเหนือ       วังทอง            9               แรงงานสร้างชาติ     2
10202   บช    ลำปาง  วังเหนือ       วังทอง            9                    ประชากรไทย     1
10203   บช    ลำปาง  วังเหนือ       วังทอง            9            ครูไทยเพื่อประชาชน   ( )
10204   บช    ลำปาง  วังเหนือ       วังทอง            9                     ประชาชาติ     1
10205   บช    ลำปาง  วังเหนือ       วังทอง            9                 สร้างอนาคตไทย   ( )
10206   บช    ลำปาง  วังเหนือ       วังทอง            9                       รักชาติ     3
10207   บช    ลำปาง  วังเหนือ       วังทอง            9                      ไทยพร้อม   NaN
10208   บช    ลำปาง  วังเหนือ       วังทอง            9                     ภูมิใจไทย    15
10209   บช    ลำปาง  วังเหนือ       วังทอง            9                  พลังธรรมใหม่     1
10210   บช    ลำปาง  วังเหนือ       วังทอง            9                          กรีน   NaN
10211   บช    ลำปาง  วังเหนือ       วังทอง            9                       ไทยธรรม   NaN
10212   บช    ลำปาง  วังเหนือ       วังทอง            9                   แผ่นดินธรรม     1
10213   บช    ลำปาง  วังเหนือ       วังทอง            9                      กล้าธรรม    26
10214   บช    ลำปาง  วังเหนือ       วังทอง            9                  พลังประชารัฐ     2
10215   บช    ลำปาง  วังเหนือ       วังทอง            9                     โอกาสใหม่   NaN
10216   บช    ลำปาง  วังเหนือ       วังทอง            9                      เป็นธรรม   NaN
10217   บช    ลำปาง  วังเหนือ       วังทอง            9                       ประชาชน    52
10218   บช    ลำปาง  วังเหนือ       วังทอง            9                      ประชาไทย   NaN
10219   บช    ลำปาง  วังเหนือ       วังทอง            9                   ไทยสร้างไทย   NaN
10220   บช    ลำปาง  วังเหนือ       วังทอง            9                   ไทยก้าวใหม่     1
10221   บช    ลำปาง  วังเหนือ       วังทอง            9                 ประชาอาสาชาติ   NaN
10222   บช    ลำปาง  วังเหนือ       วังทอง            9                         พร้อม   NaN
10223   บช    ลำปาง  วังเหนือ       วังทอง            9   เครือข่ายชาวนาแห่งประเทศไทย   NaN
10224   บช    ลำปาง  วังเหนือ       วังทอง            9                ไทยพิทักษ์ธรรม   NaN
10225   บช    ลำปาง  วังเหนือ       วังทอง            9                  ความหวังใหม่     7
10226   บช    ลำปาง  วังเหนือ       วังทอง            9                     ไทยรวมไทย   NaN
10227   บช    ลำปาง  วังเหนือ       วังทอง            9                เพื่อบ้านเมือง     1
10228   บช    ลำปาง  วังเหนือ       วังทอง            9                พลังไทยรักชาติ   NaN

In [1292]:
edit_df("ไทยทรัพย์ทวี", "ใหม่", "เพื่อชาติไทย", df)
edit_df("ใหม่", "ใหม่", "มิติใหม่", df)

✅ ไม่พบเคสที่พรรค ใหม่ อยู่ต่อจาก ไทยทรัพย์ทวี
✅ ไม่พบเคสที่พรรค ใหม่ อยู่ต่อจาก ใหม่

In [1293]:
print(df[(df['sub-district'] == 'เมืองมาย') & (df['unit_number'] == 1)].to_string())

      type province district sub-district  unit_number                          name score
17235  เขต    ลำปาง   แจ้ห่ม     เมืองมาย            1  นางสาววิชุดา ว่องวัฒนวิโรจน์     1
17236  เขต    ลำปาง   แจ้ห่ม     เมืองมาย            1          นางสาวสุวิภา กุศลจูง    19
17237  เขต    ลำปาง   แจ้ห่ม     เมืองมาย            1              นายศรีพรหม หอมยก     1
17238  เขต    ลำปาง   แจ้ห่ม     เมืองมาย            1           นายสมบูรณ์ รูปสะอาด     1
17239  เขต    ลำปาง   แจ้ห่ม     เมืองมาย            1              นายดาชัย เอกปฐพี   109
17240  เขต    ลำปาง   แจ้ห่ม     เมืองมาย            1           นายธนาธร โล่ห์สุนทร    25
17241  เขต    ลำปาง   แจ้ห่ม     เมืองมาย            1    พันเอกสันทัด ภัทรกิตตินนท์     1
19266   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                      เศรษฐกิจ     5
19267   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                    เสรีรวมไทย     4
19268   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                รวมพลังประชาชน     6
19269   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                          ใหม่     8
19270   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                      อนาคตไทย     9
19271   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                  พลังเพื่อไทย     7
19272   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                        ไทยชนะ     9
19273   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                 พลังสังคมใหม่     9
19274   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1              สังคมประชาธิปไตย     9
19275   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                        ฟิวชัน     9
19276   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                     ไทรวมพลัง     9
19277   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                     ก้าวอิสระ     9
19278   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                      ปวงชนไทย     9
19279   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                   วิชชั่นใหม่     9
19280   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                เพื่อชีวิตใหม่     9
19281   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                       คลองไทย     9
19282   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                  ประชาธิปัตย์     9
19283   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                   ไทยก้าวหน้า     9
19284   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                      ไทยภักดี     9
19285   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1               แรงงานสร้างชาติ     9
19286   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                    ประชากรไทย     9
19287   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1            ครูไทยเพื่อประชาชน     9
19288   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                     ประชาชาติ     9
19289   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                 สร้างอนาคตไทย     9
19290   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                       รักชาติ     0
19291   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                      ไทยพร้อม     0
19292   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                     ภูมิใจไทย    10
19293   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                  พลังธรรมใหม่     0
19294   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                          กรีน     0
19295   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                       ไทยธรรม     5
19296   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                   แผ่นดินธรรม     0
19297   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                      กล้าธรรม    20
19298   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                  พลังประชารัฐ     1
19299   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                     โอกาสใหม่     1
19300   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                      เป็นธรรม     1
19301   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                       ประชาชน    83
19302   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                      ประชาไทย     0
19303   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                   ไทยสร้างไทย     0
19304   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                   ไทยก้าวใหม่     0
19305   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                 ประชาอาสาชาติ     0
19306   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                         พร้อม     0
19307   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1   เครือข่ายชาวนาแห่งประเทศไทย     0
19308   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                ไทยพิทักษ์ธรรม     0
19309   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                  ความหวังใหม่     0
19310   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                     ไทยรวมไทย     0
19311   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                เพื่อบ้านเมือง     0
19312   บช    ลำปาง   แจ้ห่ม     เมืองมาย            1                พลังไทยรักชาติ     0

In [1294]:
edit_df("คลองไทย", "ประชาชน", "ประชาธิปัตย์", df)

✅ ไม่พบเคสที่พรรค ประชาชน อยู่ต่อจาก คลองไทย

In [1295]:
edit_df("คลองไทย", "ประชาชาติ", "ประชาธิปัตย์", df)

✅ ไม่พบเคสที่พรรค ประชาชาติ อยู่ต่อจาก คลองไทย

In [1296]:
print(df[(df['sub-district'] == 'แจ้ห่ม(นอกเขต)') & (df['unit_number'] == 7)].to_string())

      type province district    sub-district  unit_number                          name score
17452  เขต    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7  นางสาววิชุดา ว่องวัฒนวิโรจน์     9
17453  เขต    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7          นางสาวสุวิภา กุศลจูง   103
17454  เขต    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7              นายศรีพรหม หอมยก     4
17455  เขต    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7           นายสมบูรณ์ รูปสะอาด     9
17456  เขต    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7              นายดาชัย เอกปฐพี    80
17457  เขต    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7           นายธนาธร โล่ห์สุนทร    45
17458  เขต    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7    พันเอกสันทัด ภัทรกิตตินนท์     4
19977   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                  ไทยทรัพย์ทวี     3
19978   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                  เพื่อชาติไทย     9
19979   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                          ใหม่     2
19980   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      มิติใหม่     4
19981   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      รวมใจไทย     7
19982   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7               รวมไทยสร้างชาติ     9
19983   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                         พลวัต     -
19984   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7               ประชาธิปไตยใหม่     2
19985   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      เพื่อไทย    69
19986   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                  ทางเลือกใหม่     4
19987   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      เศรษฐกิจ     7
19988   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                    เสรีรวมไทย     2
19989   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                รวมพลังประชาชน     4
19990   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                    ท้องที่ไทย     -
19991   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      อนาคตไทย     -
19992   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                  พลังเพื่อไทย     -
19993   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                        ไทยชนะ     -
19994   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                 พลังสังคมใหม่     -
19995   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7              สังคมประชาธิปไตย     -
19996   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                        ฟิวชัน     1
19997   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                     ไทรวมพลัง     -
19998   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                     ก้าวอิสระ     -
19999   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      ปวงชนไทย     -
20000   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                   วิชชั่นใหม่     -
20001   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                เพื่อชีวิตใหม่     -
20002   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                       คลองไทย     2
20003   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                  ประชาธิปัตย์     3
20004   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                   ไทยก้าวหน้า     -
20005   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      ไทยภักดี     1
20006   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7               แรงงานสร้างชาติ     -
20007   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                    ประชากรไทย     1
20008   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7            ครูไทยเพื่อประชาชน     1
20009   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                     ประชาชาติ     -
20010   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                 สร้างอนาคตไทย     2
20011   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                       รักชาติ     -
20012   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      ไทยพร้อม     1
20013   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                     ภูมิใจไทย    15
20014   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                  พลังธรรมใหม่     2
20015   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                          กรีน     -
20016   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                       ไทยธรรม     -
20017   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                   แผ่นดินธรรม     -
20018   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      กล้าธรรม    14
20019   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                  พลังประชารัฐ     1
20020   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                     โอกาสใหม่     -
20021   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      เป็นธรรม     -
20022   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                       ประชาชน    94
20023   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                      ประชาไทย     -
20024   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                   ไทยสร้างไทย     -
20025   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                   ไทยก้าวใหม่     1
20026   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                 ประชาอาสาชาติ     -
20027   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                         พร้อม     1
20028   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7   เครือข่ายชาวนาแห่งประเทศไทย     -
20029   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                ไทยพิทักษ์ธรรม     -
20030   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                  ความหวังใหม่     1
20031   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                     ไทยรวมไทย     -
20032   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                เพื่อบ้านเมือง     1
20033   บช    ลำปาง   แจ้ห่ม  แจ้ห่ม(นอกเขต)            7                พลังไทยรักชาติ     -

In [1297]:
edit_df("สังคมประชาธิปไตย", "ใหม่", "ฟิวชัน", df)

✅ ไม่พบเคสที่พรรค ใหม่ อยู่ต่อจาก สังคมประชาธิปไตย

In [1298]:
check_from_df(df)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

📌 [บช] อำเภอ: งาว | ตำบล: นาแก | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 55 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 2 รายชื่อ: เพื่อชาติไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านแหง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 10 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 47 รายชื่อ: กรีน, กล้าธรรม, ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ความหวังใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชน, ประชาชาติ, ประชาธิปัตย์, ประชาอาสาชาติ, ประชาไทย, ปวงชนไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังสังคมใหม่, พลังเพื่อไทย, พลังไทยรักชาติ, ฟิวชัน, ภูมิใจไทย, รวมพลังประชาชน, รักชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อชีวิตใหม่, เพื่อบ้านเมือง, เศรษฐกิจ, เสรีรวมไทย, แผ่นดินธรรม, แรงงานสร้างชาติ, โอกาสใหม่, ไทยก้าวหน้า, ไทยก้าวใหม่, ไทยชนะ, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยภักดี, ไทยรวมไทย, ไทยสร้างไทย, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 12
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: หลวงใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: แม่ตีบ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ท้องที่ไทย, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังซ้าย | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทอง | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 15
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 31 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 26 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 8
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 13
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 56 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 1 รายชื่อ: ท้องที่ไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)

In [1299]:
total = 0
for district in d:
    for sd, val in d[district].items():
        total += val

In [1300]:
total

355

In [1301]:
df['sub-district'] = df['sub-district'].astype(str).str.strip()
df['unit_number'] = pd.to_numeric(df['unit_number'], errors='coerce')

print("🔍 ตามล่าหาข้อมูลที่หายไป 'ทั้งก้อน'...")

missing_whole_groups = 0

# 1. เอา Group keys ที่มีอยู่จริงใน df มาเก็บไว้ใน Set (เพื่อให้ค้นหาได้เร็วๆ)
# หน้าตาข้อมูลใน Set จะเป็นแบบ: ('นาแก', 1, 'เขต'), ('นาแก', 1, 'บช')
existing_groups = set(tuple(x) for x in df[['sub-district', 'unit_number', 'type']].dropna().drop_duplicates().values)

# 2. วนลูปตามโครงสร้างความจริงจาก Dictionary d
for district in d:
    for sd, total_units in d[district].items():
        for unit in range(1, total_units + 1): # วนลูปหน่วยที่ 1 ถึง N
            c_unit = unit
            if district == 'นอกเขต':
                c_unit = -1
            # print(sd,c_unit)
            # เช็คว่า 'เขต' ของหน่วยนี้มีใน df ไหม?
            if (sd, c_unit, 'เขต') not in existing_groups:
                missing_whole_groups += 7
                print(f"🚨 หายไปทั้งหน้า! [เขต] ตำบล: {sd} | หน่วยที่: {c_unit} (หายไป 7 รายชื่อ)")
                
            # เช็คว่า 'บช' ของหน่วยนี้มีใน df ไหม?
            if (sd, c_unit, 'บช') not in existing_groups:
                missing_whole_groups += 57
                print(f"🚨 หายไปทั้งหน้า! [บช]  ตำบล: {sd} | หน่วยที่: {c_unit} (หายไป 57 รายชื่อ)")

print("-" * 50)
print(f"✅ จำนวนรายชื่อที่หายไปเพราะหายทั้งก้อน (ไม่ได้เข้า groupby): {missing_whole_groups}")

🔍 ตามล่าหาข้อมูลที่หายไป 'ทั้งก้อน'...
🚨 หายไปทั้งหน้า! [เขต] ตำบล: บ้านเสด็จ | หน่วยที่: 19 (หายไป 7 รายชื่อ)
🚨 หายไปทั้งหน้า! [เขต] ตำบล: บ้านโป่ง | หน่วยที่: 9 (หายไป 7 รายชื่อ)
🚨 หายไปทั้งหน้า! [บช]  ตำบล: บ้านโป่ง | หน่วยที่: 9 (หายไป 57 รายชื่อ)
🚨 หายไปทั้งหน้า! [เขต] ตำบล: บ้านโป่ง | หน่วยที่: 11 (หายไป 7 รายชื่อ)
🚨 หายไปทั้งหน้า! [บช]  ตำบล: ปงเตา | หน่วยที่: 4 (หายไป 57 รายชื่อ)
🚨 หายไปทั้งหน้า! [เขต] ตำบล: ทุ่งฮั้ว | หน่วยที่: 10 (หายไป 7 รายชื่อ)
--------------------------------------------------
✅ จำนวนรายชื่อที่หายไปเพราะหายทั้งก้อน (ไม่ได้เข้า groupby): 142

In [1302]:
check_from_df(df)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

📌 [บช] อำเภอ: งาว | ตำบล: นาแก | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านร้อง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 55 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 2 รายชื่อ: เพื่อชาติไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านอ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านแหง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: บ้านโป่ง | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 10 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 47 รายชื่อ: กรีน, กล้าธรรม, ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ความหวังใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชน, ประชาชาติ, ประชาธิปัตย์, ประชาอาสาชาติ, ประชาไทย, ปวงชนไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังสังคมใหม่, พลังเพื่อไทย, พลังไทยรักชาติ, ฟิวชัน, ภูมิใจไทย, รวมพลังประชาชน, รักชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อชีวิตใหม่, เพื่อบ้านเมือง, เศรษฐกิจ, เสรีรวมไทย, แผ่นดินธรรม, แรงงานสร้างชาติ, โอกาสใหม่, ไทยก้าวหน้า, ไทยก้าวใหม่, ไทยชนะ, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยภักดี, ไทยรวมไทย, ไทยสร้างไทย, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: ปงเตา | หน่วยที่: 12
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: หลวงใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: งาว | ตำบล: แม่ตีบ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ท้องที่ไทย, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: ทุ่งฮั้ว | หน่วยที่: 11
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังซ้าย | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทรายคำ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังทอง | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังแก้ว | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: วังเหนือ | ตำบล: วังใต้ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 10
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: ทุ่งกว๋าว | หน่วยที่: 15
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 31 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 26 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 8
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: บ้านขอ | หน่วยที่: 13
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 6
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: หัวเมือง | หน่วยที่: 9
   📊 มีข้อมูลทั้งหมด 56 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 1 รายชื่อ: ท้องที่ไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: เมืองปาน | หน่วยที่: 7
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 1
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 24 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ปวงชนไทย, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, รวมพลังประชาชน, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชีวิตใหม่, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ไทยก้าวหน้า, ไทยชนะ, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 2
   📊 มีข้อมูลทั้งหมด 23 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 34 รายชื่อ: ก้าวอิสระ, ครูไทยเพื่อประชาชน, คลองไทย, ทางเลือกใหม่, ท้องที่ไทย, ประชากรไทย, ประชาชาติ, ประชาธิปัตย์, ประชาธิปไตยใหม่, ปวงชนไทย, พลวัต, พลังสังคมใหม่, พลังเพื่อไทย, ฟิวชัน, มิติใหม่, รวมพลังประชาชน, รวมใจไทย, รวมไทยสร้างชาติ, วิชชั่นใหม่, สร้างอนาคตไทย, สังคมประชาธิปไตย, อนาคตไทย, เพื่อชาติไทย, เพื่อชีวิตใหม่, เพื่อไทย, เศรษฐกิจ, เสรีรวมไทย, แรงงานสร้างชาติ, ใหม่, ไทยก้าวหน้า, ไทยชนะ, ไทยทรัพย์ทวี, ไทยภักดี, ไทรวมพลัง
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 3
   📊 มีข้อมูลทั้งหมด 47 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 10 รายชื่อ: ทางเลือกใหม่, ประชาธิปไตยใหม่, พลวัต, มิติใหม่, รวมใจไทย, รวมไทยสร้างชาติ, เพื่อชาติไทย, เพื่อไทย, ใหม่, ไทยทรัพย์ทวี
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 4
   📊 มีข้อมูลทั้งหมด 34 บรรทัด (จากที่ควรมี 57 บรรทัด)
   ❌ ขาดหายไป 23 รายชื่อ: กรีน, กล้าธรรม, ความหวังใหม่, ประชาชน, ประชาอาสาชาติ, ประชาไทย, พร้อม, พลังธรรมใหม่, พลังประชารัฐ, พลังไทยรักชาติ, ภูมิใจไทย, รักชาติ, เครือข่ายชาวนาแห่งประเทศไทย, เป็นธรรม, เพื่อบ้านเมือง, แผ่นดินธรรม, โอกาสใหม่, ไทยก้าวใหม่, ไทยธรรม, ไทยพร้อม, ไทยพิทักษ์ธรรม, ไทยรวมไทย, ไทยสร้างไทย
------------------------------------------------------------
📌 [บช] อำเภอ: เมืองปาน | ตำบล: แจ้ซ้อน | หน่วยที่: 5
   📊 มีข้อมูลทั้งหมด 33 บรรทัด (จากที่ควรมี 57 บรรทัด)

In [1303]:
# df.to_csv("master_result1.csv", index=False)

In [1304]:
df.isnull().sum()

type              0
province          0
district          0
sub-district      0
unit_number       0
name              0
score           274
dtype: int64

In [1305]:
df_result2 = pd.read_csv("master_result2.csv")
df_result2.head()

  type province district sub-district  unit_number          name score
0   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1  ไทยทรัพย์ทวี     0
1   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1  เพื่อชาติไทย     6
2   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1          ใหม่     4
3   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1      มิติใหม่     0
4   บช    ลำปาง   นอกเขต     ชุดที่ 1           -1      รวมใจไทย     1

In [1306]:
check_from_df(df_result2)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

จำนวนที่ขาดรวมคิดเป็น: 0
✅ ข้อมูลสมบูรณ์แบบ! ทุกหน่วยมีรายชื่อครบถ้วน ไม่มีขาด ไม่มีเกิน ไม่มีซ้ำครับ

In [1307]:
def check_missing_allrecord(df):
    df['sub-district'] = df['sub-district'].astype(str).str.strip()
    df['unit_number'] = pd.to_numeric(df['unit_number'], errors='coerce')
    
    print("🔍 ตามล่าหาข้อมูลที่หายไป 'ทั้งก้อน'...")
    
    missing_whole_groups = 0
    
    # 1. เอา Group keys ที่มีอยู่จริงใน df มาเก็บไว้ใน Set (เพื่อให้ค้นหาได้เร็วๆ)
    # หน้าตาข้อมูลใน Set จะเป็นแบบ: ('นาแก', 1, 'เขต'), ('นาแก', 1, 'บช')
    existing_groups = set(tuple(x) for x in df[['sub-district', 'unit_number', 'type']].dropna().drop_duplicates().values)
    
    # 2. วนลูปตามโครงสร้างความจริงจาก Dictionary d
    for district in d:
        for sd, total_units in d[district].items():
            for unit in range(1, total_units + 1): # วนลูปหน่วยที่ 1 ถึง N
                c_unit = unit
                if district == 'นอกเขต':
                    c_unit = -1
                # print(sd,c_unit)
                # เช็คว่า 'เขต' ของหน่วยนี้มีใน df ไหม?
                if (sd, c_unit, 'เขต') not in existing_groups:
                    missing_whole_groups += 7
                    print(f"🚨 หายไปทั้งหน้า! [เขต] ตำบล: {sd} | หน่วยที่: {c_unit} (หายไป 7 รายชื่อ)")
                    
                # เช็คว่า 'บช' ของหน่วยนี้มีใน df ไหม?
                if (sd, c_unit, 'บช') not in existing_groups:
                    missing_whole_groups += 57
                    print(f"🚨 หายไปทั้งหน้า! [บช]  ตำบล: {sd} | หน่วยที่: {c_unit} (หายไป 57 รายชื่อ)")
    
    print("-" * 50)
    print(f"✅ จำนวนรายชื่อที่หายไปเพราะหายทั้งก้อน (ไม่ได้เข้า groupby): {missing_whole_groups}")

In [1308]:
check_missing_allrecord(df_result2)

🔍 ตามล่าหาข้อมูลที่หายไป 'ทั้งก้อน'...
--------------------------------------------------
✅ จำนวนรายชื่อที่หายไปเพราะหายทั้งก้อน (ไม่ได้เข้า groupby): 0

Mannual above file

In [1309]:
df_result2_again = pd.read_csv("master_result2.csv")

In [1310]:
check_from_df(df_result2_again)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

จำนวนที่ขาดรวมคิดเป็น: 0
✅ ข้อมูลสมบูรณ์แบบ! ทุกหน่วยมีรายชื่อครบถ้วน ไม่มีขาด ไม่มีเกิน ไม่มีซ้ำครับ

In [1311]:
df_result2_again.isnull().sum()

type              0
province          0
district          0
sub-district      0
unit_number       0
name              0
score           274
dtype: int64

In [1312]:
df_result2_again['score'] = df_result2_again['score'].fillna("0")

In [1313]:
df_result2_again.isnull().sum()

type            0
province        0
district        0
sub-district    0
unit_number     0
name            0
score           0
dtype: int64

In [1314]:
df_result2_again['score_clean'] = df_result2_again['score']

In [1315]:
def check_string_score(df):
    invalid_score_records = df[df['score_clean'].astype(str).str.contains(r'\D', regex=True, na=False)]

    # แสดงผลเรคคอร์ดที่พบปัญหา
    print(f"พบข้อมูลที่ไม่ใช่ตัวเลขจำนวน: {len(invalid_score_records)} แถว")
    print(invalid_score_records)

In [1316]:
check_string_score(df_result2_again)

พบข้อมูลที่ไม่ใช่ตัวเลขจำนวน: 2691 แถว
      type province district sub-district  unit_number            name score  \
45      บช    ลำปาง   นอกเขต     ชุดที่ 1           -1         ประชาชน  49.7
256     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1    ไทยทรัพย์ทวี     -
257     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1    เพื่อชาติไทย    A.
258     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1            ใหม่    B.
259     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1        มิติใหม่     -
...    ...      ...      ...          ...          ...             ...   ...
22713   บช    ลำปาง   แจ้ห่ม       แม่สุก            6   ประชาอาสาชาติ     -
22714   บช    ลำปาง   แจ้ห่ม       แม่สุก            6           พร้อม     -
22716   บช    ลำปาง   แจ้ห่ม       แม่สุก            6  ไทยพิทักษ์ธรรม     -
22717   บช    ลำปาง   แจ้ห่ม       แม่สุก            6    ความหวังใหม่     -
22718   บช    ลำปาง   แจ้ห่ม       แม่สุก            6       ไทยรวมไทย     -

      score_clean
45           49.7
256             -
257            A.
258            B.
259             -
...           ...
22713           -
22714           -
22716           -
22717           -
22718           -

[2691 rows x 8 columns]

In [1317]:
df_result2_again.loc[df_result2_again['score_clean'].str.strip() == '-', 'score_clean'] = '0'

In [1318]:
check_string_score(df_result2_again)

พบข้อมูลที่ไม่ใช่ตัวเลขจำนวน: 1093 แถว
      type province district sub-district  unit_number             name score  \
45      บช    ลำปาง   นอกเขต     ชุดที่ 1           -1          ประชาชน  49.7
257     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1     เพื่อชาติไทย    A.
258     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1             ใหม่    B.
260     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1         รวมใจไทย    1.
261     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1  รวมไทยสร้างชาติ    9.
...    ...      ...      ...          ...          ...              ...   ...
21131   บช    ลำปาง   แจ้ห่ม     ทุ่งผึ้ง            8           ไทยชนะ     /
21240   บช    ลำปาง   แจ้ห่ม       แม่สุก           10       เสรีรวมไทย    .0
21264   บช    ลำปาง   แจ้ห่ม       แม่สุก           10         ไทยพร้อม    .0
21379   บช    ลำปาง   แจ้ห่ม       แม่สุก           12        ภูมิใจไทย   3.1
21388   บช    ลำปาง   แจ้ห่ม       แม่สุก           12          ประชาชน  10.8

      score_clean
45           49.7
257            A.
258            B.
260            1.
261            9.
...           ...
21131           /
21240          .0
21264          .0
21379         3.1
21388        10.8

[1093 rows x 8 columns]

In [1319]:
import pandas as pd
import re
from collections import defaultdict

def check_char2text(df):
    char_to_strings_map = defaultdict(list)

    # 2. ดึงเฉพาะข้อมูลที่ไม่ใช่ค่าว่าง (NaN) และลบค่าที่ซ้ำกันออกก่อน (เพื่อให้ทำงานเร็วขึ้น)
    unique_scores = df['score_clean'].dropna().astype(str).unique()

    # 3. วนลูปตรวจสอบทีละค่า
    for val in unique_scores:
        # re.findall(r'\D', val) จะดึง "ทุกอักขระที่ไม่ใช่ตัวเลข" ออกมาเป็นลิสต์
        # ใช้ set() ครอบอีกที เพื่อให้ได้อักขระที่ไม่ซ้ำกันใน 1 ข้อความ (เช่น " 10 " จะนับ space แค่ตัวเดียว)
        non_digits = set(re.findall(r'\D', val))

        for char in non_digits:
            char_to_strings_map[char].append(val)

    # 4. แสดงผลลัพธ์แบบสวยงาม
    print("🔍 สรุปตัวอักษรที่ไม่ใช่ตัวเลข และข้อความที่พบ:")
    print("-" * 60)
    for char, original_strings in char_to_strings_map.items():
        # จัด format ตัวอักษรให้ดูง่ายขึ้น (เช่น ถ้าเป็น space bar จะได้มองเห็น)
        display_char = f"[{char}]" if char == " " else f"'{char}'"

        print(f"อักขระ {display_char} : พบใน {len(original_strings)} รูปแบบข้อความ")

        # พิมพ์ตัวอย่างข้อความที่พบอักขระนี้ (โชว์สูงสุด 10 อันแรก จะได้ไม่รกจอเกินไป)
        print(f"   -> ตัวอย่าง: {original_strings[:10]}")
        print("-" * 60)
check_char2text(df_result2_again)

🔍 สรุปตัวอักษรที่ไม่ใช่ตัวเลข และข้อความที่พบ:
------------------------------------------------------------
อักขระ '.' : พบใน 60 รูปแบบข้อความ
   -> ตัวอย่าง: ['49.7', 'A.', 'B.', '1.', '9.', 'I.', '86.', '2.', '41.', '3.']
------------------------------------------------------------
อักขระ 'A' : พบใน 2 รูปแบบข้อความ
   -> ตัวอย่าง: ['A.', 'A']
------------------------------------------------------------
อักขระ 'B' : พบใน 2 รูปแบบข้อความ
   -> ตัวอย่าง: ['B.', 'B']
------------------------------------------------------------
อักขระ 'I' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['I.']
------------------------------------------------------------
อักขระ [ ] : พบใน 213 รูปแบบข้อความ
   -> ตัวอย่าง: ['10 (สม)', '6 (หก)', '109 (หนึ่งร้อยเก้า)', '19 (สิบเก้า)', '1 (หนึ่ง)', '200 (สองร้อย)', '70 (เจ็ดสิบ)', '5 ', '6 ', '3 ']
------------------------------------------------------------
อักขระ 'ม' : พบใน 20 รูปแบบข้อความ
   -> ตัวอย่าง: ['10 (สม)', '(สาม)', '(ยี่สิบสาม)', '( ส เม )', '( สุขุม )', '( หนึ่งร้อยสามสิบ )', '( มันย์ )', '3 (สาม)', '53 (ห้าสิบสาม)', '13 ( สิบสาม )']
------------------------------------------------------------
อักขระ ')' : พบใน 74 รูปแบบข้อความ
   -> ตัวอย่าง: ['10 (สม)', '(หนึ่ง)', '(ศูนย์)', '(สี่สิบหก)', '(ห้า)', '(สอง)', '(สาม)', '(สี่ร้อยเก้าสิบสอง)', '6 (หก)', '109 (หนึ่งร้อยเก้า)']
------------------------------------------------------------
อักขระ '(' : พบใน 76 รูปแบบข้อความ
   -> ตัวอย่าง: ['10 (สม)', '(หนึ่ง)', '(ศูนย์)', '(สี่สิบหก)', '(ห้า)', '(สอง)', '(สาม)', '(สี่ร้อยเก้าสิบสอง)', '6 (หก)', '109 (หนึ่งร้อยเก้า)']
------------------------------------------------------------
อักขระ 'ส' : พบใน 85 รูปแบบข้อความ
   -> ตัวอย่าง: ['10 (สม)', '(สี่สิบหก)', '(สอง)', '(สาม)', '(สี่ร้อยเก้าสิบสอง)', '19 (สิบเก้า)', '200 (สองร้อย)', '70 (เจ็ดสิบ)', '46 (สี่สิบหก)', '217 (สองร้อยสิบเจ็ด)']
------------------------------------------------------------
อักขระ 'b' : พบใน 5 รูปแบบข้อความ
   -> ตัวอย่าง: ['b', '11b', 'bb', 'b .', 'b.']
------------------------------------------------------------
อักขระ 'น' : พบใน 35 รูปแบบข้อความ
   -> ตัวอย่าง: ['(หนึ่ง)', '(ศูนย์)', '109 (หนึ่งร้อยเก้า)', '1 (หนึ่ง)', '0 (ศูนย์)', 'พันธุ์', 'หนึ่ง', 'ศูนย์', 'ศูนย์ สิบสอง', '( หนึ่ง )']
------------------------------------------------------------
อักขระ 'ึ' : พบใน 20 รูปแบบข้อความ
   -> ตัวอย่าง: ['(หนึ่ง)', '109 (หนึ่งร้อยเก้า)', '1 (หนึ่ง)', 'หนึ่ง', '( หนึ่ง )', '( หนึ่งร้อยสามสิบ )', '125 (หนึ่งพันสองร้อยห้า)', '124 (หนึ่งร้อยสี่สิบสี่)', '118 (หนึ่งร้อยสิบแปด)', '5 / - หนึ่ง-']
------------------------------------------------------------
อักขระ '่' : พบใน 43 รูปแบบข้อความ
   -> ตัวอย่าง: ['(หนึ่ง)', '(สี่สิบหก)', '(สี่ร้อยเก้าสิบสอง)', '109 (หนึ่งร้อยเก้า)', '1 (หนึ่ง)', '46 (สี่สิบหก)', '28 (ยี่สิบแปด)', '4 (สี่)', '25 (ยี่สิบห้า)', '284 (แปดสิบสี่)']
------------------------------------------------------------
อักขระ 'ง' : พบใน 44 รูปแบบข้อความ
   -> ตัวอย่าง: ['(หนึ่ง)', '(สอง)', '(สี่ร้อยเก้าสิบสอง)', '109 (หนึ่งร้อยเก้า)', '1 (หนึ่ง)', '200 (สองร้อย)', '217 (สองร้อยสิบเจ็ด)', '1 (หยิง)', '2 (สอง)', 'สอง']
------------------------------------------------------------
อักขระ 'ห' : พบใน 48 รูปแบบข้อความ
   -> ตัวอย่าง: ['(หนึ่ง)', '(สี่สิบหก)', '(ห้า)', '6 (หก)', '109 (หนึ่งร้อยเก้า)', '1 (หนึ่ง)', '5 (ห้า)', '46 (สี่สิบหก)', '25 (ยี่สิบห้า)', '1 (หยิง)']
------------------------------------------------------------
อักขระ '์' : พบใน 13 รูปแบบข้อความ
   -> ตัวอย่าง: ['(ศูนย์)', '0 (ศูนย์)', 'พันธุ์', 'ศูนย์', 'ศูนย์ สิบสอง', '( ศูนย์ )', '( มันย์ )', '13 (สิงคโปร์)', '0 / 1 ศูนย์', '0 / ศูนย์']
------------------------------------------------------------
อักขระ 'ศ' : พบใน 7 รูปแบบข้อความ
   -> ตัวอย่าง: ['(ศูนย์)', '0 (ศูนย์)', 'ศูนย์', 'ศูนย์ สิบสอง', '( ศูนย์ )', '0 / 1 ศูนย์', '0 / ศูนย์']
------------------------------------------------------------
อักขระ 'ู' : พบใน 8 รูปแบบข้อความ
   -> ตัวอย่าง: ['(ศูนย์)', '0 (ศูนย์)', 'ศูนย์', 'ศูนย์ สิบสอง', '( ศูนย์ )', '0 / 1 ศูนย์', '0 / ศูนย์', '0 / ก่อนบู่']
------------------------------------------------------------
อักขระ 'ย' : พบใน 30 รูปแบบข้อความ
   -> ตัวอย่าง: ['(ศูนย์)', '(สี่ร้อยเก้าสิบสอง)', '109 (หนึ่งร้อยเก้า)', '200 (สองร้อย)', '217 (สองร้อยสิบเจ็ด)', '28 (ยี่สิบแปด)', '0 (ศูนย์)', '25 (ยี่สิบห้า)', '1 (หยิง)', 'ศูนย์']
------------------------------------------------------------
อักขระ 'ิ' : พบใน 53 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สี่สิบหก)', '(สี่ร้อยเก้าสิบสอง)', '19 (สิบเก้า)', '70 (เจ็ดสิบ)', '46 (สี่สิบหก)', '217 (สองร้อยสิบเจ็ด)', '28 (ยี่สิบแปด)', '25 (ยี่สิบห้า)', '10 (สิบ)', '1 (หยิง)']
------------------------------------------------------------
อักขระ 'ี' : พบใน 23 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สี่สิบหก)', '(สี่ร้อยเก้าสิบสอง)', '46 (สี่สิบหก)', '28 (ยี่สิบแปด)', '4 (สี่)', '25 (ยี่สิบห้า)', '284 (แปดสิบสี่)', '(ยี่สิบสาม)', '(สี่ลิบทเจ็ด)', '(แปดสิบสี่)']
------------------------------------------------------------
อักขระ 'ก' : พบใน 29 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สี่สิบหก)', '(สี่ร้อยเก้าสิบสอง)', '6 (หก)', '109 (หนึ่งร้อยเก้า)', '19 (สิบเก้า)', '46 (สี่สิบหก)', '65 (หกสิบห้า)', '61 (หกสิบเอ็ด)', '76 (เจ็ดสิบหก)', '56 (ห้าสิบหก)']
------------------------------------------------------------
อักขระ 'บ' : พบใน 52 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สี่สิบหก)', '(สี่ร้อยเก้าสิบสอง)', '19 (สิบเก้า)', '70 (เจ็ดสิบ)', '46 (สี่สิบหก)', '217 (สองร้อยสิบเจ็ด)', '28 (ยี่สิบแปด)', '25 (ยี่สิบห้า)', '10 (สิบ)', '284 (แปดสิบสี่)']
------------------------------------------------------------
อักขระ '้' : พบใน 36 รูปแบบข้อความ
   -> ตัวอย่าง: ['(ห้า)', '(สี่ร้อยเก้าสิบสอง)', '109 (หนึ่งร้อยเก้า)', '19 (สิบเก้า)', '200 (สองร้อย)', '5 (ห้า)', '217 (สองร้อยสิบเจ็ด)', '25 (ยี่สิบห้า)', '( ห้า )', '( หนึ่งร้อยสามสิบ )']
------------------------------------------------------------
อักขระ 'า' : พบใน 33 รูปแบบข้อความ
   -> ตัวอย่าง: ['(ห้า)', '(สาม)', '(สี่ร้อยเก้าสิบสอง)', '109 (หนึ่งร้อยเก้า)', '19 (สิบเก้า)', '5 (ห้า)', '25 (ยี่สิบห้า)', '(ยี่สิบสาม)', '( ห้า )', '( หนึ่งร้อยสามสิบ )']
------------------------------------------------------------
อักขระ 'อ' : พบใน 35 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สอง)', '(สี่ร้อยเก้าสิบสอง)', '109 (หนึ่งร้อยเก้า)', '200 (สองร้อย)', '217 (สองร้อยสิบเจ็ด)', '2 (สอง)', 'สอง', 'ศูนย์ สิบสอง', '( ส อ )', '( หนึ่งร้อยสามสิบ )']
------------------------------------------------------------
อักขระ 'เ' : พบใน 34 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สี่ร้อยเก้าสิบสอง)', '109 (หนึ่งร้อยเก้า)', '19 (สิบเก้า)', '70 (เจ็ดสิบ)', '217 (สองร้อยสิบเจ็ด)', '(สี่ลิบทเจ็ด)', '( สิบเจ็ด )', '( ส เม )', '61 (หกสิบเอ็ด)', '76 (เจ็ดสิบหก)']
------------------------------------------------------------
อักขระ 'ร' : พบใน 17 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สี่ร้อยเก้าสิบสอง)', '109 (หนึ่งร้อยเก้า)', '200 (สองร้อย)', '217 (สองร้อยสิบเจ็ด)', '( หนึ่งร้อยสามสิบ )', '125 (หนึ่งพันสองร้อยห้า)', '13 (สิงคโปร์)', '124 (หนึ่งร้อยสี่สิบสี่)', '118 (หนึ่งร้อยสิบแปด)', '107 (หนึ่งร้อยเจ็ด)']
------------------------------------------------------------
อักขระ 'ด' : พบใน 27 รูปแบบข้อความ
   -> ตัวอย่าง: ['70 (เจ็ดสิบ)', '217 (สองร้อยสิบเจ็ด)', '28 (ยี่สิบแปด)', '284 (แปดสิบสี่)', '(สี่ลิบทเจ็ด)', '(แปดสิบสี่)', '( สิบเจ็ด )', '61 (หกสิบเอ็ด)', '76 (เจ็ดสิบหก)', '8 (แปด)']
------------------------------------------------------------
อักขระ 'จ' : พบใน 13 รูปแบบข้อความ
   -> ตัวอย่าง: ['70 (เจ็ดสิบ)', '217 (สองร้อยสิบเจ็ด)', '(สี่ลิบทเจ็ด)', '( สิบเจ็ด )', '76 (เจ็ดสิบหก)', '97 (เก้าสิบเจ็ด)', '7 (เจ็ด)', '107 (หนึ่งร้อยเจ็ด)', '47 (สี่สิบเจ็ด)', '76 / เจ็ดสิบหก']
------------------------------------------------------------
อักขระ '็' : พบใน 20 รูปแบบข้อความ
   -> ตัวอย่าง: ['70 (เจ็ดสิบ)', '217 (สองร้อยสิบเจ็ด)', '(สี่ลิบทเจ็ด)', '( สิบเจ็ด )', '61 (หกสิบเอ็ด)', '76 (เจ็ดสิบหก)', '97 (เก้าสิบเจ็ด)', '7 (เจ็ด)', '107 (หนึ่งร้อยเจ็ด)', '47 (สี่สิบเจ็ด)']
------------------------------------------------------------
อักขระ 'แ' : พบใน 11 รูปแบบข้อความ
   -> ตัวอย่าง: ['28 (ยี่สิบแปด)', '284 (แปดสิบสี่)', '(แปดสิบสี่)', '8 (แปด)', '118 (หนึ่งร้อยสิบแปด)', '18 ( สิบแปด )', '180 / 1 หนึ่งร้อยแปดสิบ', '181 / หนึ่งร้อยแปดสิบเอ็ด', '12 / ส้มแปด', '18 / ส้มแปด']
------------------------------------------------------------
อักขระ 'ป' : พบใน 13 รูปแบบข้อความ
   -> ตัวอย่าง: ['28 (ยี่สิบแปด)', '284 (แปดสิบสี่)', '(แปดสิบสี่)', '( พลังปวง )', '13 (สิงคโปร์)', '8 (แปด)', '118 (หนึ่งร้อยสิบแปด)', '18 ( สิบแปด )', '180 / 1 หนึ่งร้อยแปดสิบ', '181 / หนึ่งร้อยแปดสิบเอ็ด']
------------------------------------------------------------
อักขระ 'D' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['D']
------------------------------------------------------------
อักขระ 'O' : พบใน 2 รูปแบบข้อความ
   -> ตัวอย่าง: ['O', 'O.']
------------------------------------------------------------
อักขระ '○' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['○']
------------------------------------------------------------
อักขระ 'พ' : พบใน 3 รูปแบบข้อความ
   -> ตัวอย่าง: ['พันธุ์', '( พลังปวง )', '125 (หนึ่งพันสองร้อยห้า)']
------------------------------------------------------------
อักขระ 'ั' : พบใน 4 รูปแบบข้อความ
   -> ตัวอย่าง: ['พันธุ์', '( พลังปวง )', '( มันย์ )', '125 (หนึ่งพันสองร้อยห้า)']
------------------------------------------------------------
อักขระ 'ุ' : พบใน 3 รูปแบบข้อความ
   -> ตัวอย่าง: ['พันธุ์', '( สุขุม )', '0.( สุนย์']
------------------------------------------------------------
อักขระ 'ธ' : พบใน 2 รูปแบบข้อความ
   -> ตัวอย่าง: ['พันธุ์', '23 ( ธีสิบสาม )']
------------------------------------------------------------
อักขระ '-' : พบใน 53 รูปแบบข้อความ
   -> ตัวอย่าง: ['1-', '0-', '2-', '5-', '15/-', '21/-', '8/-', '12/-', '1/-', '3/-']
------------------------------------------------------------
อักขระ 'ท' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สี่ลิบทเจ็ด)']
------------------------------------------------------------
อักขระ 'ล' : พบใน 9 รูปแบบข้อความ
   -> ตัวอย่าง: ['(สี่ลิบทเจ็ด)', '( พลังปวง )', '7 / เล็ก', '0 / เหล็ง', '0 เหล็ก', '9 / เหลือรวยสี่สิบสอง', '1 / เหล็ง', '1 / เหล็ก', '122 / เหลือรวยสี่สิบสอง']
------------------------------------------------------------
อักขระ '/' : พบใน 89 รูปแบบข้อความ
   -> ตัวอย่าง: ['/3', '15/-', '21/-', '8/-', '12/-', '1/-', '3/-', '69/-', '2/-', '/']
------------------------------------------------------------
อักขระ 'ข' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['( สุขุม )']
------------------------------------------------------------
อักขระ 'ว' : พบใน 3 รูปแบบข้อความ
   -> ตัวอย่าง: ['( พลังปวง )', '9 / เหลือรวยสี่สิบสอง', '122 / เหลือรวยสี่สิบสอง']
------------------------------------------------------------
อักขระ 'โ' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['13 (สิงคโปร์)']
------------------------------------------------------------
อักขระ 'ค' : พบใน 4 รูปแบบข้อความ
   -> ตัวอย่าง: ['13 (สิงคโปร์)', '1 / คนส์', '0 / คนส', '0 / คนส์']
------------------------------------------------------------
อักขระ 'ซ' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['1 (เอซ)']
------------------------------------------------------------
อักขระ 'C' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['C']
------------------------------------------------------------
อักขระ '%' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['2 / - 80%']
------------------------------------------------------------
อักขระ 'o' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['o']
------------------------------------------------------------
อักขระ 'ื' : พบใน 4 รูปแบบข้อความ
   -> ตัวอย่าง: ['0 / ส้มจืด', '9 / เหลือรวยสี่สิบสอง', '17 / ส้มจืด', '122 / เหลือรวยสี่สิบสอง']
------------------------------------------------------------
อักขระ 'c' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['c']
------------------------------------------------------------

In [1320]:
# df_result2_again['score_clean'] = df_result2_again['score_clean'].astype(str).str.replace('-', '0', regex=False)

# 2. ลบเฉพาะสิ่งที่ "มั่นใจว่าเป็นขยะแน่นอน" 
# (ภาษาไทย, เครื่องหมายวงเล็บ, และช่องว่าง \s)
df_result2_again['score_clean'] = df_result2_again['score_clean'].str.replace(r'[\u0E00-\u0E7F\(\)\s]', '', regex=True)

# 3. 🚨 สร้างตัวดักจับ (Flag): เช็คว่าผลลัพธ์ที่ได้ เป็นตัวเลขล้วนๆ (0-9) หรือไม่?
# ถ้าย้ายขยะปกติออกแล้ว ยังมีตัวประหลาด (เช่น 42+6 หรือ 12.5) มันจะไม่ match เงื่อนไขนี้
is_pure_number = df_result2_again['score_clean'].str.match(r'^\d+$')

# 4. แยกข้อมูลที่ "ต้องให้คน (Manual) ช่วยดู" ออกมา
# (คือพวกที่มีเครื่องหมายแปลกๆ หลงเหลืออยู่ หรือหาเลขไม่เจอเลย)
df_needs_manual = df_result2_again[~is_pure_number]

print(f"✅ ทำความสะอาดเป็นตัวเลขสมบูรณ์: {is_pure_number.sum()} แถว")
print(f"🚨 พบข้อมูลน่าสงสัย (ต้องเปิดไฟล์ภาพดู): {len(df_needs_manual)} แถว")

# ปริ้นดูว่ามีตัวไหนบ้างที่โค้ดฟ้องให้เราเช็ค
if len(df_needs_manual) > 0:
    print(df_needs_manual[['name', 'score', 'score_clean']])

✅ ทำความสะอาดเป็นตัวเลขสมบูรณ์: 21843 แถว
🚨 พบข้อมูลน่าสงสัย (ต้องเปิดไฟล์ภาพดู): 877 แถว
                  name score score_clean
45             ประชาชน  49.7        49.7
257       เพื่อชาติไทย    A.          A.
258               ใหม่    B.          B.
260           รวมใจไทย    1.          1.
261    รวมไทยสร้างชาติ    9.          9.
...                ...   ...         ...
21131           ไทยชนะ     /           /
21240       เสรีรวมไทย    .0          .0
21264         ไทยพร้อม    .0          .0
21379        ภูมิใจไทย   3.1         3.1
21388          ประชาชน  10.8        10.8

[877 rows x 3 columns]

In [1321]:
check_char2text(df_result2_again)

🔍 สรุปตัวอักษรที่ไม่ใช่ตัวเลข และข้อความที่พบ:
------------------------------------------------------------
อักขระ '.' : พบใน 51 รูปแบบข้อความ
   -> ตัวอย่าง: ['49.7', 'A.', 'B.', '1.', '9.', 'I.', '86.', '2.', '41.', '3.']
------------------------------------------------------------
อักขระ 'A' : พบใน 2 รูปแบบข้อความ
   -> ตัวอย่าง: ['A.', 'A']
------------------------------------------------------------
อักขระ 'B' : พบใน 2 รูปแบบข้อความ
   -> ตัวอย่าง: ['B.', 'B']
------------------------------------------------------------
อักขระ 'I' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['I.']
------------------------------------------------------------
อักขระ 'b' : พบใน 4 รูปแบบข้อความ
   -> ตัวอย่าง: ['b', '11b', 'bb', 'b.']
------------------------------------------------------------
อักขระ 'D' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['D']
------------------------------------------------------------
อักขระ 'O' : พบใน 2 รูปแบบข้อความ
   -> ตัวอย่าง: ['O', 'O.']
------------------------------------------------------------
อักขระ '○' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['○']
------------------------------------------------------------
อักขระ '-' : พบใน 45 รูปแบบข้อความ
   -> ตัวอย่าง: ['1-', '0-', '2-', '5-', '15/-', '21/-', '8/-', '12/-', '1/-', '3/-']
------------------------------------------------------------
อักขระ '/' : พบใน 62 รูปแบบข้อความ
   -> ตัวอย่าง: ['/3', '15/-', '21/-', '8/-', '12/-', '1/-', '3/-', '69/-', '2/-', '/']
------------------------------------------------------------
อักขระ 'C' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['C']
------------------------------------------------------------
อักขระ '%' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['2/-80%']
------------------------------------------------------------
อักขระ 'o' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['o']
------------------------------------------------------------
อักขระ 'c' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['c']
------------------------------------------------------------

In [1322]:
# แทนที่จุด '.' ด้วยค่าว่าง '' (ลบทิ้ง)
df_result2_again['score_clean'] = df_result2_again['score_clean'].astype(str).str.replace('.', '', regex=False)
check_char2text(df_result2_again)

🔍 สรุปตัวอักษรที่ไม่ใช่ตัวเลข และข้อความที่พบ:
------------------------------------------------------------
อักขระ 'A' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['A']
------------------------------------------------------------
อักขระ 'B' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['B']
------------------------------------------------------------
อักขระ 'I' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['I']
------------------------------------------------------------
อักขระ 'b' : พบใน 3 รูปแบบข้อความ
   -> ตัวอย่าง: ['b', '11b', 'bb']
------------------------------------------------------------
อักขระ 'D' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['D']
------------------------------------------------------------
อักขระ 'O' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['O']
------------------------------------------------------------
อักขระ '○' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['○']
------------------------------------------------------------
อักขระ '-' : พบใน 45 รูปแบบข้อความ
   -> ตัวอย่าง: ['1-', '0-', '2-', '5-', '15/-', '21/-', '8/-', '12/-', '1/-', '3/-']
------------------------------------------------------------
อักขระ '/' : พบใน 61 รูปแบบข้อความ
   -> ตัวอย่าง: ['/3', '15/-', '21/-', '8/-', '12/-', '1/-', '3/-', '69/-', '2/-', '/']
------------------------------------------------------------
อักขระ 'C' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['C']
------------------------------------------------------------
อักขระ '%' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['2/-80%']
------------------------------------------------------------
อักขระ 'o' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['o']
------------------------------------------------------------
อักขระ 'c' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['c']
------------------------------------------------------------

In [1323]:
# 1. สร้างเงื่อนไขป้องกัน: เลือกเฉพาะแถวที่ไม่ได้มีแค่ '-' ตัวเดียวโดดๆ
mask_not_lone_dash = df_result2_again['score_clean'].astype(str).str.strip() != '-'

# 2. ตัดหาง: เจอ / หรือ - ตรงไหน ให้ลบทิ้งไปจนจบข้อความ
# r'[/-].*' หมายถึง "เจอ / หรือ - และอักขระอะไรก็ตามที่ตามหลังมัน (.*) ให้จับรวบแล้วลบทิ้งให้หมด"
df_result2_again.loc[mask_not_lone_dash, 'score_clean'] = (
    df_result2_again.loc[mask_not_lone_dash, 'score_clean']
    .astype(str)
    .str.replace(r'[/-].*', '', regex=True)
)

# 3. ลบช่องว่างหน้า-หลังที่อาจจะหลงเหลืออยู่ (เช่น "126 /-" พอโดนตัดอาจจะเหลือ "126 ")
df_result2_again['score_clean'] = df_result2_again['score_clean'].str.strip()

In [1324]:
check_string_score(df_result2_again)

พบข้อมูลที่ไม่ใช่ตัวเลขจำนวน: 121 แถว
      type province district sub-district  unit_number             name score  \
257     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1     เพื่อชาติไทย    A.
258     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1             ใหม่    B.
263     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1  ประชาธิปไตยใหม่    I.
297     บช    ลำปาง   นอกเขต    ชุดที่ 13           -1         กล้าธรรม     A
394     บช    ลำปาง   นอกเขต     ชุดที่ 3           -1         เศรษฐกิจ     b
...    ...      ...      ...          ...          ...              ...   ...
18693   บช    ลำปาง   แจ้ห่ม        ปงดอน            6        ภูมิใจไทย     A
18697   บช    ลำปาง   แจ้ห่ม        ปงดอน            6      แผ่นดินธรรม     O
18702   บช    ลำปาง   แจ้ห่ม        ปงดอน            6          ประชาชน     B
19408   บช    ลำปาง   แจ้ห่ม     วิเชตนคร            7         เศรษฐกิจ     b
21058   บช    ลำปาง   แจ้ห่ม     ทุ่งผึ้ง            7     ไทยทรัพย์ทวี     A

      score_clean
257             A
258             B
263             I
297             A
394             b
...           ...
18693           A
18697           O
18702           B
19408           b
21058           A

[121 rows x 8 columns]

In [1325]:
check_char2text(df_result2_again)

🔍 สรุปตัวอักษรที่ไม่ใช่ตัวเลข และข้อความที่พบ:
------------------------------------------------------------
อักขระ 'A' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['A']
------------------------------------------------------------
อักขระ 'B' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['B']
------------------------------------------------------------
อักขระ 'I' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['I']
------------------------------------------------------------
อักขระ 'b' : พบใน 3 รูปแบบข้อความ
   -> ตัวอย่าง: ['b', '11b', 'bb']
------------------------------------------------------------
อักขระ 'D' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['D']
------------------------------------------------------------
อักขระ 'O' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['O']
------------------------------------------------------------
อักขระ '○' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['○']
------------------------------------------------------------
อักขระ 'C' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['C']
------------------------------------------------------------
อักขระ 'o' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['o']
------------------------------------------------------------
อักขระ '-' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['-']
------------------------------------------------------------
อักขระ 'c' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['c']
------------------------------------------------------------

In [1326]:
df_result2_again.isnull().sum()

type            0
province        0
district        0
sub-district    0
unit_number     0
name            0
score           0
score_clean     0
dtype: int64

In [1327]:
df_result2_again.loc[(df_result2_again['score_clean'] == 'o') | (df_result2_again['score_clean'] == 'O'), 'score_clean'] = '0'

In [1328]:
check_string_score(df_result2_again)

พบข้อมูลที่ไม่ใช่ตัวเลขจำนวน: 56 แถว
      type province    district sub-district  unit_number              name  \
257     บช    ลำปาง      นอกเขต    ชุดที่ 13           -1      เพื่อชาติไทย
258     บช    ลำปาง      นอกเขต    ชุดที่ 13           -1              ใหม่
263     บช    ลำปาง      นอกเขต    ชุดที่ 13           -1   ประชาธิปไตยใหม่
297     บช    ลำปาง      นอกเขต    ชุดที่ 13           -1          กล้าธรรม
394     บช    ลำปาง      นอกเขต     ชุดที่ 3           -1          เศรษฐกิจ
1908    บช    ลำปาง         งาว     บ้านร้อง           11          เศรษฐกิจ
2103    บช    ลำปาง         งาว     บ้านร้อง            2           รักชาติ
2104    บช    ลำปาง         งาว     บ้านร้อง            2          ไทยพร้อม
2107    บช    ลำปาง         งาว     บ้านร้อง            2              กรีน
2108    บช    ลำปาง         งาว     บ้านร้อง            2           ไทยธรรม
2111    บช    ลำปาง         งาว     บ้านร้อง            2      พลังประชารัฐ
2112    บช    ลำปาง         งาว     บ้านร้อง            2         โอกาสใหม่
3908    บช    ลำปาง         งาว    หลวงเหนือ            2          เศรษฐกิจ
3965    บช    ลำปาง         งาว    หลวงเหนือ            3          เศรษฐกิจ
4136    บช    ลำปาง         งาว    หลวงเหนือ            6          เศรษฐกิจ
4297    บช    ลำปาง         งาว      หลวงใต้            2      ไทยทรัพย์ทวี
5588    บช    ลำปาง         งาว     บ้านโป่ง            7      ไทยทรัพย์ทวี
6421    บช    ลำปาง         งาว        ปงเตา            9          เพื่อไทย
7493    บช    ลำปาง    วังเหนือ     ทุ่งฮั้ว            5         ภูมิใจไทย
7825    บช    ลำปาง    วังเหนือ     บ้านใหม่            2      ประชาธิปัตย์
7868    บช    ลำปาง    วังเหนือ     บ้านใหม่            3    รวมพลังประชาชน
7882    บช    ลำปาง    วังเหนือ     บ้านใหม่            3      ประชาธิปัตย์
8118    บช    ลำปาง    วังเหนือ     ร่องเคาะ           11           รักชาติ
8228    บช    ลำปาง    วังเหนือ     ร่องเคาะ           13        ประชากรไทย
8688    บช    ลำปาง    วังเหนือ     ร่องเคาะ            4           รักชาติ
9061    บช    ลำปาง    วังเหนือ      วังซ้าย           10          เพื่อไทย
9686    บช    ลำปาง    วังเหนือ    วังทรายคำ            3       แผ่นดินธรรม
9687    บช    ลำปาง    วังเหนือ    วังทรายคำ            3          กล้าธรรม
9861    บช    ลำปาง    วังเหนือ    วังทรายคำ            7          เศรษฐกิจ
10318   บช    ลำปาง    วังเหนือ       วังทอง            7          เศรษฐกิจ
10319   บช    ลำปาง    วังเหนือ       วังทอง            7        เสรีรวมไทย
10322   บช    ลำปาง    วังเหนือ       วังทอง            7          อนาคตไทย
10326   บช    ลำปาง    วังเหนือ       วังทอง            7  สังคมประชาธิปไตย
10327   บช    ลำปาง    วังเหนือ       วังทอง            7            ฟิวชัน
10328   บช    ลำปาง    วังเหนือ       วังทอง            7         ไทรวมพลัง
10330   บช    ลำปาง    วังเหนือ       วังทอง            7          ปวงชนไทย
10335   บช    ลำปาง    วังเหนือ       วังทอง            7       ไทยก้าวหน้า
10337   บช    ลำปาง    วังเหนือ       วังทอง            7   แรงงานสร้างชาติ
12881   บช    ลำปาง    เมืองปาน    ทุ่งกว๋าว            8        ประชากรไทย
13056   บช    ลำปาง    เมืองปาน     หัวเมือง            3          เศรษฐกิจ
13172   บช    ลำปาง    เมืองปาน     หัวเมือง            5    รวมพลังประชาชน
13194   บช    ลำปาง    เมืองปาน     หัวเมือง            5           รักชาติ
13206   บช    ลำปาง    เมืองปาน     หัวเมือง            5          ประชาไทย
13248   บช    ลำปาง    เมืองปาน     หัวเมือง            6          กล้าธรรม
13280   บช    ลำปาง    เมืองปาน     หัวเมือง            7      ประชาธิปัตย์
15054   บช    ลำปาง    เมืองปาน     เมืองปาน            3          เศรษฐกิจ
15070   บช    ลำปาง    เมืองปาน     เมืองปาน            3      ประชาธิปัตย์
15791   บช    ลำปาง  เมืองลำปาง    บ้านเสด็จ           12     พลังสังคมใหม่
16002   บช    ลำปาง  เมืองลำปาง    บ้านเสด็จ           16          เศรษฐกิจ
16266   บช    ลำปาง  เมืองลำปาง    บ้านเสด็จ            2    พลังไทยรักชาติ
16479   บช    ลำปาง  เมืองลำปาง    บ้านเสด็จ            6          กล้าธรรม
16893   บช    ลำปาง  เมืองลำปาง      บ้านแลง            2          เศรษฐกิจ
18693   บช    ลำปาง      แจ้ห่ม        ปงดอน            6         ภูมิใจไทย
18702   บช    ลำปาง      แจ้ห่ม        ปงดอน            6           ประชาชน
19408   บช    ลำปาง      แจ้ห่ม     วิเชตนคร            7          เศรษฐกิจ
21058   บช    ลำปาง      แจ้ห่ม     ทุ่งผึ้ง            7      ไทยทรัพย์ทวี

      score score_clean
257      A.           A
258      B.           B
263      I.           I
297       A           A
394       b           b
1908      D           D
2103      ○           ○
2104      ○           ○
2107      ○           ○
2108      ○           ○
2111      ○           ○
2112      ○           ○
3908      A           A
3965      A           A
4136      b           b
4297      A           A
5588      b           b
6421    11b         11b
7493      b           b
7825      b           b
7868      A           A
7882      b           b
8118      D           D
8228      C           C
8688      b           b
9061     bb          bb
9686      C           C
9687      b           b
9861      b           b
10318   b .           b
10319    -.           -
10322    -.           -
10326    -.           -
10327    -.           -
10328    -.           -
10330    -.           -
10335    -.           -
10337    -.           -
12881     A           A
13056     b           b
13172    b.           b
13194     A           A
13206     D           D
13248     A           A
13280     A           A
15054     b           b
15070     A           A
15791     A           A
16002     b           b
16266     c           c
16479     A           A
16893     A           A
18693     A           A
18702     B           B
19408     b           b
21058     A           A

In [1329]:
check_char2text(df_result2_again)

🔍 สรุปตัวอักษรที่ไม่ใช่ตัวเลข และข้อความที่พบ:
------------------------------------------------------------
อักขระ 'A' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['A']
------------------------------------------------------------
อักขระ 'B' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['B']
------------------------------------------------------------
อักขระ 'I' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['I']
------------------------------------------------------------
อักขระ 'b' : พบใน 3 รูปแบบข้อความ
   -> ตัวอย่าง: ['b', '11b', 'bb']
------------------------------------------------------------
อักขระ 'D' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['D']
------------------------------------------------------------
อักขระ '○' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['○']
------------------------------------------------------------
อักขระ 'C' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['C']
------------------------------------------------------------
อักขระ '-' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['-']
------------------------------------------------------------
อักขระ 'c' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['c']
------------------------------------------------------------

In [1330]:
df_result2_again.loc[df_result2_again['score_clean'] == '-', :]

,type,province,district,sub-district,unit_number,name,score,score_clean
10319,บช,ลำปาง,วังเหนือ,วังทอง,7,เสรีรวมไทย,-.,-
10322,บช,ลำปาง,วังเหนือ,วังทอง,7,อนาคตไทย,-.,-
10326,บช,ลำปาง,วังเหนือ,วังทอง,7,สังคมประชาธิปไตย,-.,-
10327,บช,ลำปาง,วังเหนือ,วังทอง,7,ฟิวชัน,-.,-
10328,บช,ลำปาง,วังเหนือ,วังทอง,7,ไทรวมพลัง,-.,-
10330,บช,ลำปาง,วังเหนือ,วังทอง,7,ปวงชนไทย,-.,-
10335,บช,ลำปาง,วังเหนือ,วังทอง,7,ไทยก้าวหน้า,-.,-
10337,บช,ลำปาง,วังเหนือ,วังทอง,7,แรงงานสร้างชาติ,-.,-

In [1331]:
df_result2_again.loc[df_result2_again['score_clean'].str.strip() == '-', 'score_clean'] = '0' 
df_result2_again.loc[df_result2_again['score_clean'] == '-', :]

Empty DataFrame
Columns: [type, province, district, sub-district, unit_number, name, score, score_clean]
Index: []

In [1332]:
df_result2_again.loc[df_result2_again['score_clean'] == "A", "score_clean"] = '4'

In [1333]:
df_result2_again.loc[df_result2_again['score_clean'] == "B", "score_clean"] = '3'
df_result2_again['score_clean'] = df_result2_again['score_clean'].astype(str).str.replace('b', '6', regex=False)

In [1334]:
check_char2text(df_result2_again)
check_string_score(df_result2_again)

🔍 สรุปตัวอักษรที่ไม่ใช่ตัวเลข และข้อความที่พบ:
------------------------------------------------------------
อักขระ 'I' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['I']
------------------------------------------------------------
อักขระ 'D' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['D']
------------------------------------------------------------
อักขระ '○' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['○']
------------------------------------------------------------
อักขระ 'C' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['C']
------------------------------------------------------------
อักขระ 'c' : พบใน 1 รูปแบบข้อความ
   -> ตัวอย่าง: ['c']
------------------------------------------------------------
พบข้อมูลที่ไม่ใช่ตัวเลขจำนวน: 13 แถว
      type province    district sub-district  unit_number             name  \
263     บช    ลำปาง      นอกเขต    ชุดที่ 13           -1  ประชาธิปไตยใหม่
1908    บช    ลำปาง         งาว     บ้านร้อง           11         เศรษฐกิจ
2103    บช    ลำปาง         งาว     บ้านร้อง            2          รักชาติ
2104    บช    ลำปาง         งาว     บ้านร้อง            2         ไทยพร้อม
2107    บช    ลำปาง         งาว     บ้านร้อง            2             กรีน
2108    บช    ลำปาง         งาว     บ้านร้อง            2          ไทยธรรม
2111    บช    ลำปาง         งาว     บ้านร้อง            2     พลังประชารัฐ
2112    บช    ลำปาง         งาว     บ้านร้อง            2        โอกาสใหม่
8118    บช    ลำปาง    วังเหนือ     ร่องเคาะ           11          รักชาติ
8228    บช    ลำปาง    วังเหนือ     ร่องเคาะ           13       ประชากรไทย
9686    บช    ลำปาง    วังเหนือ    วังทรายคำ            3      แผ่นดินธรรม
13206   บช    ลำปาง    เมืองปาน     หัวเมือง            5         ประชาไทย
16266   บช    ลำปาง  เมืองลำปาง    บ้านเสด็จ            2   พลังไทยรักชาติ

      score score_clean
263      I.           I
1908      D           D
2103      ○           ○
2104      ○           ○
2107      ○           ○
2108      ○           ○
2111      ○           ○
2112      ○           ○
8118      D           D
8228      C           C
9686      C           C
13206     D           D
16266     c           c

In [1335]:
df_result2_again.loc[df_result2_again['score_clean'] == "I", "score_clean"] = '1'
df_result2_again.loc[df_result2_again['score_clean'] == "D", "score_clean"] = '0'
df_result2_again.loc[df_result2_again['score_clean'] == "○", "score_clean"] = '0'
df_result2_again.loc[df_result2_again['score_clean'] == "C", "score_clean"] = '0'
df_result2_again.loc[df_result2_again['score_clean'] == "c", "score_clean"] = '0'

In [ ]:
df_result2_again.loc[df_result2_again['score_clean'] == '', 'score_clean'] = '0'

418
419
420
421
422
        ..
20514
20515
20516
20517
21131
Name: score_clean, Length: 246, dtype: str

In [1336]:
check_char2text(df_result2_again)
check_string_score(df_result2_again)

🔍 สรุปตัวอักษรที่ไม่ใช่ตัวเลข และข้อความที่พบ:
------------------------------------------------------------
พบข้อมูลที่ไม่ใช่ตัวเลขจำนวน: 0 แถว
Empty DataFrame
Columns: [type, province, district, sub-district, unit_number, name, score, score_clean]
Index: []

In [1338]:
mask_target = (df_result2_again['district'] == 'วังเหนือ') & (df_result2_again['sub-district'] == 'ทุ่งฮั้ว')

# 2. ดึงค่า unit_number ปัจจุบันออกมา และบังคับให้เป็นตัวเลข (int) เผื่อมันติดเป็น string อยู่
current_units = df_result2_again.loc[mask_target, 'unit_number'].astype(int)

# 3. ใช้คณิตศาสตร์สลับค่า: (จำนวนหน่วยสูงสุด + 1) - เลขเดิม -> ในที่นี้คือ 13 - เลขเดิม
reversed_units = 13 - current_units

# 4. เขียนค่าที่สลับแล้วกลับลงไปใน DataFrame
df_result2_again.loc[mask_target, 'unit_number'] = reversed_units

# ==========================================
# ตรวจสอบผลลัพธ์ว่าสลับถูกต้องหรือไม่
# ==========================================
print("✅ สลับหน่วย อำเภอวังเหนือ ตำบลทุ่งฮั้ว เรียบร้อยแล้ว!")
# สุ่มแสดงผลลัพธ์เพื่อตรวจสอบความถูกต้อง
print(df_result2_again[mask_target][['district', 'sub-district', 'unit_number', 'name', 'score_clean']].head(10))

✅ สลับหน่วย อำเภอวังเหนือ ตำบลทุ่งฮั้ว เรียบร้อยแล้ว!
      district sub-district  unit_number                          name  \
6519  วังเหนือ     ทุ่งฮั้ว           12  นางสาววิชุดา ว่องวัฒนวิโรจน์
6520  วังเหนือ     ทุ่งฮั้ว           12          นางสาวสุวิภา กุศลจูง
6521  วังเหนือ     ทุ่งฮั้ว           12              นายศรีพรหม หอมยก
6522  วังเหนือ     ทุ่งฮั้ว           12           นายสมบูรณ์ รูปสะอาด
6523  วังเหนือ     ทุ่งฮั้ว           12              นายดาชัย เอกปฐพี
6524  วังเหนือ     ทุ่งฮั้ว           12           นายธนาธร โล่ห์สุนทร
6525  วังเหนือ     ทุ่งฮั้ว           12    พันเอกสันทัด ภัทรกิตตินนท์
6526  วังเหนือ     ทุ่งฮั้ว            3  นางสาววิชุดา ว่องวัฒนวิโรจน์
6527  วังเหนือ     ทุ่งฮั้ว            3          นางสาวสุวิภา กุศลจูง
6528  วังเหนือ     ทุ่งฮั้ว            3              นายศรีพรหม หอมยก

     score_clean
6519           6
6520          59
6521           5
6522           3
6523          85
6524          44
6525           1
6526           6
6527          36
6528           6

In [1339]:
check_from_df(df_result2_again)

🔍 เริ่มตรวจสอบความครบถ้วนและความถูกต้องของรายชื่อ...

จำนวนที่ขาดรวมคิดเป็น: 0
✅ ข้อมูลสมบูรณ์แบบ! ทุกหน่วยมีรายชื่อครบถ้วน ไม่มีขาด ไม่มีเกิน ไม่มีซ้ำครับ

In [1345]:
df_result2_again['score_clean'] = df_result2_again['score_clean'].str.strip()

In [1346]:
df_result2_again['score_clean'] = df_result2_again['score_clean'].astype(int)

ValueError: invalid literal for int() with base 10: ''

In [1341]:
df_result2_again.to_csv("master_result3.csv", index=False)